### ISSUE TITLE
[Feature] Beauty the log when lack of dependence

### ISSUE THREAD

**Issue by Nioolek** [open-mmlab/mmengine#1000]
### What is the feature?

相关的issue：
https://github.com/open-mmlab/mmyolo/issues/663

mmyolo的用户指出，在mmyolo里跨库调用mmrotate时，由于未安装mmrotate，产生了error：
`KeyError: 'mmrotate.RotLocalVisualizer is not in the visualizer registry.`
这个log容易让人误解，不知道如何解决。
希望mmengine能做出一些优化，先判断一下mmrotate有没有安装，如果没有安装，log中提示让用户安装mmrotate。如果已经安装了mmrotate，再提示对应的模块没有注册。

**Comment by zhouzaida** [comment]
Thank you for your feedback, we will optimize the error reporting tips.
感谢你的反馈，我们会去优化报错提示。

**Comment by zhouzaida** [comment]
closed by #1010
