### ISSUE TITLE
mmengine - WARNING - Failed to import mmpose.models, please check the location of the registry model is correct.

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmengine#1003]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

 ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 11.4, V11.4.48'), ('GCC', 'gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0'), ('PyTorch', '1.10.2'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.3\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.2\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n'), ('TorchVision', '0.11.3'), ('OpenCV', '4.7.0'), ('MMEngine', '0.7.0')])

### Reproduces the problem - code sample

I ran the training program using mmpose, but encountered this error。
````
03/17 10:53:32 - mmengine - WARNING - Failed to import mmpose.models, please check the location of the registry model is correct.
python-BaseException
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/site-packages/mmengine/registry/registry.py", line 325, in switch_scope_and_registry
    yield registry
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'TopdownPoseEstimator is not in the model registry. Please check whether the value of `TopdownPoseEstimator` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
Backend TkAgg is interactive backend. Turning interactive mode on.
````
No matter which configuration file I run, the same error will be reported.". I checked the TopdownPoseEstimator in mmpose, which is located in mmpose/models/pose_ estimators/__ init__. "There is already a registration in mmpose/models/pose_estimators/__init__.py
![image](https://user-images.githubusercontent.com/90760124/225802138-56afe72f-9f75-41d8-b6ec-ef55156f5d2f.png)
which seems to be a problem that is not registered in MMEngine.". Is it caused by the incompatibility between the latest mmpose v1. x and MMEngine?

### Reproduces the problem - command or script

For detailed information, please refer to：
https://github.com/open-mmlab/mmpose/issues/2079

### Reproduces the problem - error message

````
03/17 10:53:32 - mmengine - WARNING - Failed to import mmpose.models, please check the location of the registry model is correct.
python-BaseException
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/site-packages/mmengine/registry/registry.py", line 325, in switch_scope_and_registry
    yield registry
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'TopdownPoseEstimator is not in the model registry. Please check whether the value of `TopdownPoseEstimator` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
Backend TkAgg is interactive backend. Turning interactive mode on.
````

**Comment by zhouzaida** [comment]
Resolved by https://github.com/open-mmlab/mmpose/issues/2079
