### ISSUE TITLE
[Feature] Support using list or tuple to build ConcatDataset

### ISSUE THREAD

**Issue by acdart** [open-mmlab/mmengine#1008]
### What is the feature?

support directly using list or tuple to build ConcatDataset

in openmmlab 1.0:
`
if isinstance(cfg, (list, tuple)): 
     dataset = ConcatDataset([build_dataset(c, default_args) for c in cfg])
`
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/builder.py#L71
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/builder.py#L62

**Comment by zhouzaida** [comment]
How about using `ConcatDataset`?

```python
dataset_cfg = {
    'type': 'ConcatDataset',
    'datasets': [dataset1, dataset2],
}
```
