### ISSUE TITLE
[Bug] __getitem__ in InstanceData raise an Exception on mlu device

### ISSUE THREAD

**Issue by zero0kiriyu** [open-mmlab/mmengine#1009]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

mmcv 2.0.0rc4, MLU370-X8,mmengine 0.6.0,mmyolo 0.4.0,mmdet 3.0.0rc6

### Reproduces the problem - code sample

mmcv 2.0.0rc4, MLU370-X8,mmengine 0.6.0,mmyolo 0.4.0,mmdet 3.0.0rc6

### Reproduces the problem - command or script

mmcv 2.0.0rc4, MLU370-X8,mmengine 0.6.0,mmyolo 0.4.0,mmdet 3.0.0rc6

### Reproduces the problem - error message

This code in mmdet raise an AssertionError

https://github.com/open-mmlab/mmdetection/blob/61dd8d518b13c7ee4bdf609595b7e803f3ac0224/mmdet/models/dense_heads/base_dense_head.py#L474

which is casued by 

https://github.com/open-mmlab/mmengine/blob/cbb671403f0a549c28bf66c2bd1a0bbc0ca5af16/mmengine/structures/instance_data.py#L168

This assertion works fine under the Nvidia gpu and common cpu, but it does not consider the device such as MLU.
On MLU, the batched_nms op in mmcv would return a tensor with torch.Tensor type. Maybe you can add this type to the assertion, or change the data type that batched_nms return on MLU

**Comment by zhouzaida** [comment]
Hi @zero0kiriyu , thanks for your report. We are working on improving support for MLU devices.
