### ISSUE TITLE
[feature] stopping training, changing something minor in config, resuming training.

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmengine#1029]
### What is the feature?

Sometimes, I realize I want a short validation interval mid training. 

I've realized if I stop the training, make a config modification, resume the training, my modification gets ignored.

Question 1)
Is there a way to modify a training parameter mid-traning ?

Question 2)
Which file is used for resuming previous training config hyperparamters ? `./work_dir/iter_xx.pth` ? or maybe `./work_dir/myconfig.py` ?

**Comment by zhouzaida** [comment]
Hi, which part of the config did you modify?

**Comment by joihn** [comment]
Hi, I changed `VAL_INTERVAL`

```
train_cfg = dict(
    type='IterBasedTrainLoop', max_iters=100000, val_interval=VAL_INTERVAL)
```
If only some element can be changed mid training, I would be interrested to know which ones.

**Comment by zhouzaida** [comment]
Hi, any modification in the config file should work. The logic to resume can be found at https://github.com/open-mmlab/mmengine/blob/83c4f3e643eaa16dfb847461ca5e025417718bc3/mmengine/runner/runner.py#L1926-#L2029
