### ISSUE TITLE
[Feature] test and validation batch size > 1

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmengine#1030]
### What is the feature?

I'm running mmseg 1.x.
when my validation batch is > 1 I get the follwoing message:
`AssertionError: Batch inference is not support currently, as the image size might be different in a batch`

with batch=1, my validation is quite slow. I wish there was a way to force it (all my img have the same size)

**Comment by xiexinch** [comment]
Hi @joihn,
You might try to follow our [document](https://mmsegmentation.readthedocs.io/en/main/advanced_guides/add_models.html#add-new-data-preprocessor) to implement a new data preprocessor.
