### ISSUE TITLE
[Bug] Can not save part of the model when overwrite `state_dict()`.

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmengine#1040]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

mmengine 0.7.0

### Reproduces the problem - code sample

```python
@MODELS.register_module()
class LoRAModel(BaseModel):
    def __init__(self, 
                 model: dict, 
                 r: float, 
                 alpha: float, 
                 dropout: float):
        super().__init__()
        with lora(r=r, alpha=alpha, dropout=dropout, enabled=True):
            print_log('Building model with LoRA', logger='current')
            self.model = MODELS.build(model)
            mark_only_lora_as_trainable(self.model)
        self.data_preprocessor = self.model.data_preprocessor
        
    def forward(self, *args, **kwargs):
        return self.model(*args, **kwargs)
    
    def state_dict(self, *args, **kwargs):
        return lora_state_dict(self.model)
    
    def load_state_dict(self, *args, **kwargs):
        return self.model.load_state_dict(*args, **kwargs)
```

### Reproduces the problem - command or script

pass

### Reproduces the problem - error message

pass

### Additional information

`Runner.save_checkpoint` gets the model state dict by `mmengine.runner.checkpoint.get_state_dict`.
https://github.com/open-mmlab/mmengine/blob/83c4f3e643eaa16dfb847461ca5e025417718bc3/mmengine/runner/checkpoint.py#L659-L700

It always saves the entire model which makes parameter-efficient tuning unavailable with mmengine.

**Comment by HAOCHENYE** [comment]
Solved by #595
