### ISSUE TITLE
[Bug] Can not register `partial` function or class to the registry. 

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmengine#1041]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

mmengine 0.7.0

### Reproduces the problem - code sample

```python
llama_configs = {
    '7B': dict(n_layer=32, n_head=32, n_embd=4096, block_size=4096, vocab_size=32000),
    '13B': dict(n_layer=40, n_head=40, n_embd=5120, block_size=4096, vocab_size=32000),
    '30B': dict(n_layer=60, n_head=52, n_embd=6656, block_size=4096, vocab_size=32000),
    '65B': dict(n_layer=80, n_head=64, n_embd=8192, block_size=4096, vocab_size=32000),
}


MODELS.register_module('LLaMA-7B', module=partial(LLaMA, **llama_configs['7B']))
MODELS.register_module('LLaMA-13B', module=partial(LLaMA, **llama_configs['13B']))
MODELS.register_module('LLaMA-30B', module=partial(LLaMA, **llama_configs['30B']))
MODELS.register_module('LLaMA-65B', module=partial(LLaMA, **llama_configs['65B']))
```

### Reproduces the problem - command or script

pass

### Reproduces the problem - error message

pass

**Comment by zhouzaida** [comment]
closed by #595
