### ISSUE TITLE
[Bug] MMSeparateDistributedDataParallel skip init_weights

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmengine#1042]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Reproduces the problem - code sample

I encountered this problem when running my own custom project based on `mmengine`, which is too complicated to present.

### Additional information

The `MMSeparateDistributedDataParallel` is a **model wrapper of model wrapper**, whose `module` may contain the `MMDistributedDataParallel`.

https://github.com/open-mmlab/mmengine/blob/4d7a29342c02d78cb3ffabe036607e801d6713d9/mmengine/model/wrappers/seperate_distributed.py#L82-L87

When initializing the model_wrapper weights, the `runner` initialize the weight of the `runner.model.module`:
 https://github.com/open-mmlab/mmengine/blob/4d7a29342c02d78cb3ffabe036607e801d6713d9/mmengine/runner/runner.py#L893-L902
The above codes will cause the `init_weights` functions in model not work because the children module of the `runner.model.module` in this case is of type `MMDistributedDataParallel` which does NOT have `init_weights` function.

**Comment by zhouzaida** [comment]
Hi, the module is defined in https://github.com/open-mmlab/mmengine/blob/4d7a29342c02d78cb3ffabe036607e801d6713d9/mmengine/model/wrappers/seperate_distributed.py#L71

Therefore, if you implement the `init_weights` method in the module, the runner can call it as expected.

**Comment by makecent** [comment]
@zhouzaida But the sub_modules in `self.module` are **modified** to be model_wrapper `MMDistributedDataParallel`:
https://github.com/open-mmlab/mmengine/blob/4d7a29342c02d78cb3ffabe036607e801d6713d9/mmengine/model/wrappers/seperate_distributed.py#L75-L87
Therefore, the `MMSeparateDistributedDataParallel.module` does have `init_weights` function but its sub-modules ( `MMDistributedDataParallel`) do not have `init_weights` function, which causes the `init_weights` functions of the module wrapped in the `MMDistributedDataParallel` not accessible during the initialzation.

**Comment by zhouzaida** [comment]
Oh, the init_weights method is defined in the sub-module, so there might be an issue with that.

**Comment by HAOCHENYE** [comment]
@makecent Hi, I create a [PR](#1045),  will this solve the problem?

**Comment by makecent** [comment]
@HAOCHENYE LGTM. The initialization works as expected with the PR.
