### ISSUE TITLE
[Docs] get_logger func how to get it in new mmcv or new mmengine? 

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmengine#1069]
### 📚 The doc issue

Searched all forum didn't found a new way to import it?

**Comment by jinfagang** [comment]
old one: from mmcv.utils import get_logger

**Comment by zhouzaida** [comment]
Hi @jinfagang , does the `print_log` meet your demand? https://mmengine.readthedocs.io/en/latest/api/generated/mmengine.logging.print_log.html#mmengine.logging.print_log

**Comment by jinfagang** [comment]
@zhouzaida hi, how to using print_log replace old get_logger func in mmhuman3d? I found some of mmlab project are so inconsistent to the base toolchain, I don't want different project using different mmengine or old mmcv.

**Comment by zhouzaida** [comment]
Hi, you can use the below way to get the logger.

```python
from mmengine.logging import MMLogger
logger = MMLogger.get_current_instance()
```
