### ISSUE TITLE
[Feature] Support comparing two `Config`.

### ISSUE THREAD

**Issue by HAOCHENYE** [open-mmlab/mmengine#1076]
### What is the feature?

MMEngine should add a function to compare

```python
cfg1 = Config.fromfile('cfg1')     #  cfg1 = dict(a=1, b=2)
cfg2 = Config.fromfile('cfg2')     #  #  cfg1 = dict(a=1, b=3)

Config.diff(cfg1, cfg2)
```

The result should be:
```bash
dict(a=1, b=2)  # the b=2 should be red
```

**Comment by IRONICBo** [comment]
Is the result returned by diff based on cfg1 or cfg2? For example, if cfg1 is a subset of cfg2, if cfg1 is returned, cfg1 may not show the difference in red above.

For example cfg1=dict(a=1), cfg2=dict(a=1,b=2)

**Comment by HAOCHENYE** [comment]
The formatting of the diff results requires further refinement and design. The example provided in the issue should not be taken as the final design.

In my opinion, the format of the `git diff` results is understandable and useful :rofl: .

**Comment by gachiemchiep** [comment]
@HAOCHENYE 

Using python's difflib library, I can generate a diff as git style.  

* command

```python
cfg1 = Config.fromfile('config1.py')     #  cfg1 = dict(a=1, b=2)
cfg2 = Config.fromfile('config2.py')     #  #  cfg1 = dict(a=1, b=3)
print(Config.diff(cfg1, cfg2))
```

* output

```bash
--- 

+++ 

@@ -12,7 +12,7 @@

         num_classes=10,
         in_channels=512,
         loss=dict(type='CrossEntropyLoss', loss_weight=1.0)))
-dataset_type = 'CIFAR10'
+dataset_type = 'CIFAR100'
 data_preprocessor = dict(
     num_classes=10,
     mean=[
@@ -38,7 +38,7 @@

     batch_size=16,
     num_workers=2,
     dataset=dict(
-        type='CIFAR10',
+        type='CIFAR100',
         data_prefix='data/cifar10',
         test_mode=False,
         pipeline=[
@@ -51,7 +51,7 @@

     batch_size=16,
     num_workers=2,
     dataset=dict(
-        type='CIFAR10',
+        type='CIFAR100',
         data_prefix='data/cifar10/',
         test_mode=True,
         pipeline=[
@@ -63,7 +63,7 @@

     batch_size=16,
     num_workers=2,
     dataset=dict(
-        type='CIFAR10',
+        type='CIFAR100',
         data_prefix='data/cifar10/',
         test_mode=True,
         pipeline=[
@@ -71,4 +71,19 @@

         ]),
     sampler=dict(type='DefaultSampler', shuffle=False))
 test_evaluator = dict(type='Accuracy', topk=(1, ))
+visualizer = dict(
+    type='UniversalVisualizer',
+    vis_backends=[
+        dict(type='LocalVisBackend'),
+        dict(type='TensorboardVisBackend'),
+        dict(
+            type='ClearMLVisBackend',
+            init_kwargs=dict(
+                project_name='test_clearml', task_name='resnet18 cifar10'),
+            artifact_suffix=(
+                '.py',
+                'yaml',
+                '.pth',
+            )),
+    ])
```
* config files: 
[config1.py.csv](https://github.com/open-mmlab/mmengine/files/12010673/config1.py.csv)
[config2.py.csv](https://github.com/open-mmlab/mmengine/files/12010675/config2.py.csv)

**Comment by HAOCHENYE** [comment]
> @HAOCHENYE
> 
> Using python's difflib library, I can generate a diff as git style.
> 
> * command
> 
> ```python
> cfg1 = Config.fromfile('config1.py')     #  cfg1 = dict(a=1, b=2)
> cfg2 = Config.fromfile('config2.py')     #  #  cfg1 = dict(a=1, b=3)
> print(Config.diff(cfg1, cfg2))
> ```
> 
> * output
> 
> ```shell
> --- 
> 
> +++ 
> 
> @@ -12,7 +12,7 @@
> 
>          num_classes=10,
>          in_channels=512,
>          loss=dict(type='CrossEntropyLoss', loss_weight=1.0)))
> -dataset_type = 'CIFAR10'
> +dataset_type = 'CIFAR100'
>  data_preprocessor = dict(
>      num_classes=10,
>      mean=[
> @@ -38,7 +38,7 @@
> 
>      batch_size=16,
>      num_workers=2,
>      dataset=dict(
> -        type='CIFAR10',
> +        type='CIFAR100',
>          data_prefix='data/cifar10',
>          test_mode=False,
>          pipeline=[
> @@ -51,7 +51,7 @@
> 
>      batch_size=16,
>      num_workers=2,
>      dataset=dict(
> -        type='CIFAR10',
> +        type='CIFAR100',
>          data_prefix='data/cifar10/',
>          test_mode=True,
>          pipeline=[
> @@ -63,7 +63,7 @@
> 
>      batch_size=16,
>      num_workers=2,
>      dataset=dict(
> -        type='CIFAR10',
> +        type='CIFAR100',
>          data_prefix='data/cifar10/',
>          test_mode=True,
>          pipeline=[
> @@ -71,4 +71,19 @@
> 
>          ]),
>      sampler=dict(type='DefaultSampler', shuffle=False))
>  test_evaluator = dict(type='Accuracy', topk=(1, ))
> +visualizer = dict(
> +    type='UniversalVisualizer',
> +    vis_backends=[
> +        dict(type='LocalVisBackend'),
> +        dict(type='TensorboardVisBackend'),
> +        dict(
> +            type='ClearMLVisBackend',
> +            init_kwargs=dict(
> +                project_name='test_clearml', task_name='resnet18 cifar10'),
> +            artifact_suffix=(
> +                '.py',
> +                'yaml',
> +                '.pth',
> +            )),
> +    ])
> ```
> 
> * config files:
>   [config1.py.csv](https://github.com/open-mmlab/mmengine/files/12010673/config1.py.csv)
>   [config2.py.csv](https://github.com/open-mmlab/mmengine/files/12010675/config2.py.csv)

This format seems great! Would you like to open a Pull Request to help up support it?

**Comment by gachiemchiep** [comment]
@HAOCHENYE  I created a PR at : https://github.com/open-mmlab/mmengine/pull/1260
