### ISSUE TITLE
[Bug] Cannot infer the network of mmpretrain and mmsegmentation at the same time

### ISSUE THREAD

**Issue by YangHaomiao** [open-mmlab/mmengine#1105]
### Prerequisite

- [x] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [x] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

OrderedDict([('sys.platform', 'win32'), ('Python', '3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]'), ('CUDA available', True), ('numpy_random_seed', 
2147483648), ('GPU 0', 'T600'), ('CUDA_HOME', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2'), ('NVCC', 'Cuda compilation tools, release 11.2, V11.2.67'
), ('MSVC', '用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30148 版'), ('GCC', 'n/a'), ('PyTorch', '1.9.1+cu111'), ('PyTorch compiling details', 'PyTorch built with:
\n  - C++ Version: 199711\n  - MSVC 192829337\n  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications\n  - I
ntel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)\n  - OpenMP 2019\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.1\n  - NVCC architectur
e flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=c
ompute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_3
7\n  - CuDNN 8.0.5\n  - Magma 2.5.4\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/
sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_
NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_C
UDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, \n'), ('To
rchVision', '0.10.1+cu111'), ('OpenCV', '4.7.0'), ('MMEngine', '0.7.2')])

### Reproduces the problem - code sample

import mmpretrain as pr
import mmseg.apis as seg

img_path = './204.jpg'

config_file = '../mmpretrain/configs/yhm/distance_cls2.py'
checkpoint_file = '../mmpretrain/work_dirs/distance_cls2/epoch_200.pth'
model_cls = pr.get_model(config_file, checkpoint_file, device="cuda:0") 

config_file = '../mmsegmentation/configs/yhm/transfomerseg_high.py'
checkpoint_file = '../mmsegmentation/work_dirs/transfomerseg_high/DataSet11_2k_iter.pth'
model_seg = seg.init_model(config_file1, checkpoint_file1, device='cuda:0')

result1 = seg.inference_model(model_seg, img_path)
result2 = pr.inference_model(model_cls, img_path)

### Reproduces the problem - command or script

just run code above

### Reproduces the problem - error message

Loads checkpoint by local backend from path: ../mmpretrain/work_dirs/distance_cls2/epoch_200.pth
e:\yhm\mmsegmentation\mmseg\models\builder.py:36: UserWarning: ``build_loss`` would be deprecated soon, please use ``mmseg.registry.MODELS.build()`` 
  warnings.warn('``build_loss`` would be deprecated soon, please use '
Loads checkpoint by local backend from path: ../mmsegmentation/work_dirs/transfomerseg_high/DataSet11_2k_iter.pth
Traceback (most recent call last):
  File "E:\YHM\TcpTest\test.py", line 46, in <module>
    result2 = pr.inference_model(model_cls, img_path)
  File "e:\yhm\mmpretrain\mmpretrain\apis\model.py", line 326, in inference_model
    inferencer = ImageClassificationInferencer(model, **kwargs)
  File "e:\yhm\mmpretrain\mmpretrain\apis\image_classification.py", line 84, in __init__
    self.pipeline = self._init_pipeline(self.config)
  File "e:\yhm\mmpretrain\mmpretrain\apis\image_classification.py", line 132, in _init_pipeline
    [TRANSFORMS.build(t) for t in test_pipeline_cfg])
  File "e:\yhm\mmpretrain\mmpretrain\apis\image_classification.py", line 132, in <listcomp>
    [TRANSFORMS.build(t) for t in test_pipeline_cfg])
  File "C:\Users\HP\.conda\envs\mmlab\lib\site-packages\mmengine\registry\registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\HP\.conda\envs\mmlab\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'ResizeEdge is not in the transform registry. Please check whether the value of `ResizeEdge` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by HAOCHENYE** [comment]
Hi, you should use [MMSegInferencer](https://github.com/open-mmlab/mmsegmentation/blob/e64548fda0221ad708f5da29dc907e51a644c345/mmseg/apis/mmseg_inferencer.py#L27) and [MMPoseInferencer](https://github.com/open-mmlab/mmpose/blob/dab2fdf09dc2ef21f4725d7549469a28cc718da2/mmpose/apis/inferencers/mmpose_inferencer.py#L25) to perform inference.
