### ISSUE TITLE
[Bug] Register class from child registry into parent

### ISSUE THREAD

**Issue by mmeendez8** [open-mmlab/mmengine#1111]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

`OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'NVIDIA GeForce RTX 3070 Laptop GPU'), ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 11.1, V11.1.74'), ('GCC', 'x86_64-linux-gnu-gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0'), ('PyTorch', '2.0.0+cu118'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.8\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90\n  - CuDNN 8.7\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.1+cu118'), ('OpenCV', '4.5.5'), ('MMEngine', '0.7.2')])`

### Reproduces the problem - code sample

```python
from mmcv.transforms import LoadAnnotations
from mmseg.registry import TRANSFORMS
from mmengine.dataset import Compose

@TRANSFORMS.register_module()
class MyLoader(LoadAnnotations):
    def transform(self, results: dict):
        return results


pipeline = [dict(type="MyLoader")]
Compose(pipeline)
assert "MyLoader" in TRANSFORMS # This should True
```

### Reproduces the problem - command or script

```shell
python example.py
```

### Reproduces the problem - error message

```
KeyError                                  Traceback (most recent call last)
Cell In[2], line 4
      1 from mmengine.dataset import Compose
      3 pipeline = [dict(type="MyLoader")]
----> 4 Compose(pipeline)
      6 assert "MyLoader" in TRANSFORMS # This is True

File ~/.cache/pypoetry/virtualenvs/ai-homography-estimation-MIZJYHGs-py3.8/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py:37, in Compose.__init__(self, transforms)
     33 for transform in transforms:
     34     # `Compose` can be built with config dict with type and
     35     # corresponding arguments.
     36     if isinstance(transform, dict):
---> 37         transform = TRANSFORMS.build(transform)
     38         if not callable(transform):
     39             raise TypeError(f'transform should be a callable object, '
     40                             f'but got {type(transform)}')

File ~/.cache/pypoetry/virtualenvs/ai-homography-estimation-MIZJYHGs-py3.8/lib/python3.8/site-packages/mmengine/registry/registry.py:545, in Registry.build(self, cfg, *args, **kwargs)
    523 def build(self, cfg: dict, *args, **kwargs) -> Any:
    524     """Build an instance.
    525 
    526     Build an instance by calling :attr:`build_func`.
   (...)
    543         >>> model = MODELS.build(cfg)
    544     """
--> 545     return self.build_func(cfg, *args, **kwargs, registry=self)

File ~/.cache/pypoetry/virtualenvs/ai-homography-estimation-MIZJYHGs-py3.8/lib/python3.8/site-packages/mmengine/registry/build_functions.py:100, in build_from_cfg(cfg, registry, default_args)
     98     obj_cls = registry.get(obj_type)
     99     if obj_cls is None:
--> 100         raise KeyError(
    101             f'{obj_type} is not in the {registry.name} registry. '
    102             f'Please check whether the value of `{obj_type}` is '
    103             'correct or it was registered as expected. More details '
    104             'can be found at '
    105             'https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'  # noqa: E501
    106         )
    107 elif inspect.isclass(obj_type) or inspect.isfunction(obj_type):
    108     obj_cls = obj_type

KeyError: 'MyLoader is not in the transform registry. Please check whether the value of `MyLoader` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

```

### Additional information

I understand I am using the CHILD registry (mmseg.TRANSFORMS) from the parent registry (mmengine.TRANSFORMS). 
When I create a new pipeline with `MyLoader` this returns an error, since the parent registry can't notice the child was modified. So how things that are added in mmseg.transforms, can be properly instantiated in a dataset? The dataset base class is using the same Compose as my previous example
https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/datasets/basesegdataset.py#L139

* Note I opened this issue in mmseg first, but it seems this is the correct repo:
https://github.com/open-mmlab/mmsegmentation/issues/2954

**Comment by mmeendez8** [comment]
It seems the first bullet point from this comment is what I was looking for:
https://github.com/open-mmlab/mmengine/issues/1100#issuecomment-1522826222

> Switch to the target registry: build_from_cfg is commonly called by a Regitry object, such as DATASETS defined in MMEngine. However, MMEngine does not implement any specific dataset, and the dataset is actually implemented and registered into the registry of downstream repos. Therefore, MMEngine needs to [switch](https://github.com/open-mmlab/mmengine/blob/cdec4cbd4acbabca6cc3bc7bb0866b9a67d8f401/mmengine/registry/build_functions.py#L95) to the Registry from MMEngine to MMPretrain according to the scope(scope is initialized [here](https://github.com/open-mmlab/mmengine/blob/cdec4cbd4acbabca6cc3bc7bb0866b9a67d8f401/mmengine/runner/runner.py#L370)) which is defined in default_runtime.py for searching the target class.

This is nice, I think is worth it to add it to the registry docs page since I was reading that yesterday but could not get this key thing. Happy to send a PR if needed!

**Comment by HAOCHENYE** [comment]
Thank you for your feedback :smile: . Indeed, our documentation falls short when it comes to describing the Registry section. We would greatly appreciate it if you could help us improve this part of the documentation from your perspective. Additionally, I think the ·__contains__· method of the Registry is somewhat flawed, as it should only indicate whether the module is in the current registry, rather than triggering a search process.
