### ISSUE TITLE
[Docs]How to get the value of random seed? 

### ISSUE THREAD

**Issue by Shiyang980713** [open-mmlab/mmengine#1147]
### 📚 The doc issue

I know random seed can be set by `randomness.seed=1234`. If `randomness.seed=None` and I run a experiment, how do i know the the seed used in the experiment?

**Comment by Shiyang980713** [comment]
yes, but if i dont set `randomness.seed=0`, the randomn seed is recorded as `None` in the log

```2023/05/15 20:56:38 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.9.0 (default, Nov 15 2020, 14:28:56) [GCC 7.3.0]
    CUDA available: True
    numpy_random_seed: 1350420283
    GPU 0,1,2,3,4,5,6,7: GeForce RTX 3090
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.3, V11.3.58
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.12.1+cu113
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.13.1+cu113
    OpenCV: 4.7.0
    MMEngine: 0.7.3

Runtime environment:
    cudnn_benchmark: True
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
```

**Comment by Shiyang980713** [comment]
how do I know the seed that used in this situation?

**Comment by zhouzaida** [comment]
Hi @Shiyang980713 , you can get it by `runner.seed`.

https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L548

**Comment by Shiyang980713** [comment]
> 
So in an experiment where no random seed is specified, the random seed value is not recorded in the log by default?

**Comment by Shiyang980713** [comment]
> Hi @Shiyang980713 , you can get it by `runner.seed`.
> 
> https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L548
> 
> BTW, the seed should be printed in the log so we can update it here.
> 
> https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L2307
> 
> Are you willing to submit a PR to fix this error?

Ok, I'm willing to submit a PR

**Comment by zhouzaida** [comment]
> > 
> 
> So in an experiment where no random seed is specified, the random seed value is not recorded in the log by default?

yes, it should be recorded but not.

**Comment by zfli-xdu** [comment]
> Hi @Shiyang980713 , you can get it by `runner.seed`.
> 
> https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L548
> 
> BTW, the seed should be printed in the log so we can update it here.
> 
> https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L2307
> 
> Are you willing to submit a PR to fix this error?

hi, how can i get the runner instance if i want to access some properties like seed?

**Comment by I3ab** [comment]
> > Hi @Shiyang980713 , you can get it by `runner.seed`.
> > https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L548
> > 
> > BTW, the seed should be printed in the log so we can update it here.
> > https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L2307
> > 
> > Are you willing to submit a PR to fix this error?
> 
> hi, how can i get the runner instance if i want to access some properties like seed?

hi, @zfli-xdu 
You can find examples in  examples /distributed_training.py
Basically, runner instance can be obtained as follows:
```python
from mmengine.runner import Runner
runner = Runner.from_cfg(cfg)
```

**Comment by Shiyang980713** [comment]
> > Hi @Shiyang980713 , you can get it by `runner.seed`.
> > https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L548
> > 
> > BTW, the seed should be printed in the log so we can update it here.
> > https://github.com/open-mmlab/mmengine/blob/ec2e00ae9060572de96759ef141254d352134d39/mmengine/runner/runner.py#L2307
> > 
> > Are you willing to submit a PR to fix this error?
> 
> hi, how can i get the runner instance if i want to access some properties like seed?

hi, @zfli-xdu 
You can find examples in  examples /distributed_training.py
Basically, runner instance can be obtained as follows:
```python
from mmengine.runner import Runner
runner = Runner.from_cfg(cfg)
```

**Comment by zfli-xdu** [comment]
> 

Thanks for your reply. Maybe I didn't make the question clear. 
I'm not trying to figure out how to instantiate <Runner>, but to revisit the <Runner> instance which was already instantiated. In that way, I might be able to access the properties of the <Runner> instance anywhere.
