### ISSUE TITLE
[Feature] Limit the number of logged params for MLFlow Visbackend

### ISSUE THREAD

**Issue by KickCellarDoor** [open-mmlab/mmengine#1156]
### What is the feature?

MLFlow has a 500 limit for logged parameters, while for most of the openmmlab projects, the config file contains more than 500 parameters. I think we should add an option to choose which parameters to log to the MLFlow tracking server.

```python
@force_init_env
def add_config(self, config: Config, **kwargs) -> None:
    """Record the config to mlflow.

    Args:
        config (Config): The Config object
    """
    self.cfg = config
    log_keys = [''model"]
    log_cfg = dict()
    for k in log_keys:
        log_cfg[k] = config[k]
    self._mlflow.log_params(self._flatten(log_cfg))
    self._mlflow.log_text(self.cfg.pretty_text, 'config.py')
```

Something like this, but the log keys parameters should be passed through the vis_backend config.

**Comment by zhouzaida** [comment]
Hi @KickCellarDoor , thanks for your feedback. We can add a new parameter in https://github.com/open-mmlab/mmengine/blob/4bc2fe1aaec2d7d1464b11d50f6165494f62ef18/mmengine/visualization/vis_backend.py#L661-L662 and Are you interesting in submitting a commit to support it?
