### ISSUE TITLE
[Feature] Keep the latest checkpoint only to save disk space.

### ISSUE THREAD

**Issue by DapengFeng** [open-mmlab/mmengine#1165]
### What is the feature?

Keep the latest checkpoint only to save disk space.

**Comment by zhouzaida** [comment]
Hi, mmengine has supported this feature. You can set `max_keep_ckpts=1` in `CheckpointHook`.

https://github.com/open-mmlab/mmengine/blob/277b5308803e7db08953c342064d17d414cdbe7d/mmengine/hooks/checkpoint_hook.py#L43-L46

**Comment by DapengFeng** [comment]
Thx.

**Comment by zhouzaida** [comment]
More usages about `CheckpointHook` can be found at https://mmengine.readthedocs.io/en/latest/tutorials/hook.html#checkpointhook.
