### ISSUE TITLE
[GLCC] 2023  GitLink CodeCamp 编程夏令营 

### ISSUE THREAD

**Issue by OpenMMLab-Coordinator** [open-mmlab/mmengine#1174]
## 什么是 GLCC？
第二届 GitLink 确实开源编程夏令营（GLCC）是由 CCF 中国计算机学会主办，之江实验室承办，CCF 开源发展委员会与 GitLink 确实开源社区共同协办的面向全国高校学生的暑期编程夏令营活动。
高校学生参加 GLCC OpenMMLab 的课题，入选后可获得 OpenMMLab 开源专家 1V1 指导、9000~12000RMB 不等的丰厚奖金(税前)及结项证书，心动不如行动，赶紧点击下方申请链接报名吧！

# 题目名称
## 实现 Recorder 模块，无需修改模型代码便可记录任意层的输出

# 题目描述
## 项目介绍
MMEngine 是一个基于 PyTorch 实现的，用于训练深度学习模型的基础库。它为开发人员提供了坚实的工程基础，以此避免在工作流上编写冗余代码。作为 OpenMMLab 所有代码库的训练引擎，其在不同研究领域支持了上百个算法。此外，MMEngine 也可以用于非 OpenMMLab 项目中。

## 编码任务
1. 在 MMEngine 中实现一个 Recorder 模块，可非侵入式记录模型任意层的输出。可参考 https://github.com/open-mmlab/mmrazor/tree/main/mmrazor/models/task_modules/recorder
2. 在 MMDet 和 MMRazor 验证 Recorder 模块

## 技能要求和编程语言
Python
PyTorch

## 可参与人数
1人（项目由个人独立完成，限学生参与，包括应届毕业生）

## 课题难度
中

## 项目奖金
9,000

## 申请链接
https://www.gitlink.org.cn/glcc/2023/subjects/detail/636

## 导师及联系方式
GitHub ID：[zhouzaida](https://github.com/zhouzaida)
Email：openmmlab@gmail.com

## 官方微信群
![image](https://github.com/open-mmlab/mmengine/assets/95968830/d2837b31-fa31-4f0d-bea8-cf396f82f826)

## 报名须知
1.GLCC 面向 18 岁以上的在校学生，需提交在校学生证明材料，组委会会对提交材料进行审核。
2.申请阶段，GLCC 允许每个学生同时提交最多 2 个课题申请。申请结束后，经过与课题导师双向沟通，每个学生最终只能选择完成一个课题。
3.GLCC 的每个课题都公布了导师的姓名/ID 和邮箱地址，建议提前通过邮件方式和导师建立联系，反复沟通后再提交申请材料，你有充足的时间去了解你将要承担的课题。
4.请在截止日期前三天完成提交，避免因最后大量学生提交申请导致网络拥堵。
5.学生申请指南：GLCC 为同学们申请过程中遇到的问题提供了丰富的辅导文档，可在官网查看“帮助文档-->学生指南”获取。（官网链接：https://www.gitlink.org.cn/glcc/help）
**GLCC 学生交流群**
![image](https://github.com/open-mmlab/mmagic/assets/95968830/ea982954-18ee-4c8f-9822-837b8f22c194)

**Comment by AmosChenYQ** [comment]
请问这个项目跟开源之夏的项目有关吗？

**Comment by zhouzaida** [comment]
> 请问这个项目跟开源之夏的项目有关吗？

没有关系的

**Comment by OpenMMLab-Coordinator** [comment]
> 

这个项目是由 CCF 发起的夏令营活动。整体形式和奖励是和开源之夏相当的。
欢迎同学的关注，这里是该活动的官网 https://www.gitlink.org.cn/glcc。
该课题正在审核中，待课题上线后，将在issue里更新课题链接。
同学也可以先加入交流群，对项目保持关注。
