### ISSUE TITLE
[Bug] multiple annotation files not acceptible

### ISSUE THREAD

**Issue by ccomkhj** [open-mmlab/mmengine#1177]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

torch               2.0.1
torchaudio          2.0.2
torchvision         0.15.2

### Reproduces the problem - code sample

```
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file=[
            data_root + "/mmdet/train/train_20230327.json",
            data_root + "/mmdet/train/train_20230213.json",
            data_root + "/mmdet/train/train.json",
        ],
        data_prefix=dict(img=data_root + "/mmdet/train/images/",),
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        pipeline=train_pipeline,
        backend_args=backend_args))
```

### Reproduces the problem - command or script

python train.py {config_file}.py

### Reproduces the problem - error message

```
FileNotFoundError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `CocoPlantDataset` in mmdet/datasets/coco.py: [Errno 2] No such file or directory: 
"['/{rootpath}/mmdet/train/train_20230327.json', '/{rootpath}/mmdet/train/train_20230213.json', '/{rootpath}/mmdet/train/train.json']"
```

### Additional information

Similar to previous version of mmdetection, I can deal with multiple ann_file in list format.

**Comment by HAOCHENYE** [comment]
Hi, if you need to handle multiple annotation files in MMDetection, it depends on the specific implementation of MMDet. It would be helpful to post an issue on the MMDet GitHub repository.

**Comment by HAOCHENYE** [comment]
Hi, I close the issue now, please feel free to reopen it :smile:
