### ISSUE TITLE
[Feature]增加推理时控制rich彩色条是否显示的功能

### ISSUE THREAD

**Issue by gy-7** [open-mmlab/mmengine#1182]
### What is the feature?

在使用mmpretrain进行推理时，我有一个要推理21w+图片的任务，但是rich的彩色条很影响我的控制台输出。导致我无法看到一些日志信息，希望能够增加一个控制是否显示的变量。
<img width="623" alt="f681a92b3b73a71be84d0c2e9ad4de9" src="https://github.com/open-mmlab/mmengine/assets/64619863/d46d7801-3e13-452c-93bb-b7637447e829">

**Comment by zhouzaida** [comment]
You can disable the progress by setting `show_progress=False`. https://github.com/open-mmlab/mmengine/blob/9d9f2b761ed6288a326c8963f32dc54b0dad0a62/mmengine/infer/infer.py#LL126C22-L126C22
