### ISSUE TITLE
[Bug] raise from none?

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmengine#1186]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

not important

### Reproduces the problem - code sample

not important

### Reproduces the problem - command or script

not important

### Reproduces the problem - error message

not important

### Additional information

Why do we use `raise from None` in this line? https://github.com/open-mmlab/mmengine/blob/main/mmengine/runner/runner.py#L1785

This basically means that error traces in all underlying hooks are hidden from the user :( It's much better without `from None`.

**Comment by HAOCHENYE** [comment]
Hi, this code snippet will be optimized in this [PR](https://github.com/open-mmlab/mmengine/pull/971/files), and we'll merge it ASAP

**Comment by filaPro** [comment]
Thx.
