### ISSUE TITLE
[Feature] Key 'epoch' for the dictionary "teg" in 'LogProcessor.get_log_after_epoch'

### ISSUE THREAD

**Issue by SakhnevichKirill** [open-mmlab/mmengine#1194]
### What is the feature?

To display metrics along the x-axis in "wandb" for the returned dictionary "teg" in the "get_log_after_epoch" function, the key 'epoch' is required.

```Python
cur_epoch = self._get_epoch(runner, mode)
tag['epoch'] = cur_epoch
```

**Comment by HAOCHENYE** [comment]
Sorry for my late reply. #1099 should have implemented this function.
