### ISSUE TITLE
[Feature] Add `unbind()` to InstanceData

### ISSUE THREAD

**Issue by mypydl** [open-mmlab/mmengine#1214]
### What is the feature?

Add `unbind()` to InstanceData.

When `InstanceData` is used as the parameter of `multi_apply`, the number of dimensions will remain the same after slice, which requires an additional `squeeze(0)` operation.

### Any other context?

```python
class InstanceData(BaseDataElement):
    def unbind(self):
        """
        Returns:
            :`InstanceList`: Corresponding values.
        """
        new_data_list = [self.__class__(metainfo=self.metainfo) for _ in range(len(self))]
        for key, values in self.items():
            values = [*values]
            for new_data, value in zip(new_data_list, values):
                new_data[key] = value
        return new_data_list  # type:ignore
```

**Comment by HAOCHENYE** [comment]
Do you mean splitting one `InstanceData` to `n` `InstanceData`, and the n `InstanceData` share the same squeezed data?  If so, its function makes me confused somehow.

**Comment by mypydl** [comment]
For example, 
```python
tensor = InstanceData(torch.randn(3, 5, 2)
outputs1, *_ = multi_apply(func, tensor)
```
In func, the shape of tensor_ will be [1, 5, 2]. But I want it to be [5, 2].

**Comment by HAOCHENYE** [comment]
Usually we'll pass a list of `InstanceData` to `multi_apply` like [here](https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/mmdet/models/dense_heads/anchor_head.py#L382).

So when do we need to pass the instance data directly to the `multi_apply` ?

**Comment by mypydl** [comment]
It is actually an intermediate process, which is a shortcut when I want to quickly separate multiple instances from a batch output.
For example,
```python
outputs = InstanceData(tensor1=torch.randn(6, 3, 5), tensor2=torch.randn(6, 3, 10))
batch_outputs = outputs.unbind()
# batch_outputs[0].tensor.shape will be [3, 5]
```
Especially useful, when I only need the outputs of last layer of transformer decoder.

**Comment by mypydl** [comment]
It is actually an intermediate process, which is a shortcut when I want to quickly separate multiple instances from a batch outputs.
For example:
```python
raw_outputs = InstanceData(tensor1=torch.randn(6, 3, 20), tensor2=torch.randn(6, 3, 2))
batch_outputs = raw_outputs.unbind()
# batch_outputs[0].tensor1.shape will be [3, 20]
```

**Comment by HAOCHENYE** [comment]
For this situation, we recommend using the "List of Instance data" to represent the label information for a batch. The subclasses of BaseDataelement are currently mainly used to describe the label information of individual samples.
