### ISSUE TITLE
[Bug] cannot build custom transforms in custom Dataset

### ISSUE THREAD

**Issue by YuEn-git** [open-mmlab/mmengine#1287]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0,1,2,3', 'NVIDIA GeForce RTX 2080 Ti'), ('CUDA_HOME', '/mnt/A/hust_2d/miniconda3/envs/mmseg'), ('NVCC', 'Cuda compilation tools, release 11.6, V11.6.124'), ('GCC', 'gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0'), ('PyTorch', '1.13.0'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.6\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.3.2  (built against CUDA 11.5)\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.14.0'), ('OpenCV', '4.8.0'), ('MMEngine', '0.8.2')])

### Reproduces the problem - code sample

lanetask.py ::
@TRANSFORMS.register_module()
class LoadLaneAnnos(BaseTransform):
    def __init__(self) -> None:
        super().__init__()

    def transform(self, results: Dict):
        results['extrinsic'] = np.array(results['extrinsic'], dtype=np.float32)
        results['intrinsic'] = np.array(results['intrinsic'], dtype=np.float32)
        ori_lanelines = results['lanelines']
        laneline_array = np.vstack([np.array(lane['xzv'], dtype=np.float32) for lane in ori_lanelines]) #[3*N_lane, N_points]
        cate_array = np.array([lane['category'] for lane in ori_lanelines], dtype=np.int8) #[N_lane]
        results['lanelines'] =  dict(xzv_s=laneline_array, cates=cate_array)
        return results

main.py :
from lanetask.py import *
if __name__ == '__main__':
    cfg = Config.fromfile('config/temp_configs.py')
    # t = TRANSFORMS.build(cfg.transform)  
    dataset = DATASETS.build(cfg.dataset)
    datas = next(iter(dataset))
    print('a')

temp_configs.py::
input_size = (360, 480)
dataset=dict(
        type='OpenLaneDataset',
        data_root='/mnt/B/LeY/OpenLane-Dataset/',
        ann_file = 'data_annotations/OpenLane_lane3d_300_training_mmtype.pkl',
        data_prefix=dict(),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadLaneAnnos'),
            dict(type='Resize', img_scale=(input_size[1], input_size[0]), keep_ratio=False),
        ])

### Reproduces the problem - command or script

I cannot constract custom transforms in custom Dataset. I have tried "custom_import" and import my custom moudles in main.py but both of them didn't work. However, I can build custom transforms in main.py through `TRANSFORMS.build().`

### Reproduces the problem - error message

"class `OpenLaneDataset` in LaneDataset/openlane.py: 'LoadLaneAnnos is not in the transform registry. Please check whether the value of `LoadLaneAnnos` is correct or it was registered as expected.

### Additional information

Thanks for your excellent work. Looking forward to your reply.

**Comment by fanqiNO1** [comment]
Sorry that I cannot reproduce your error.
Can you provide the full `main.py` and `lanetask.py`?

**Comment by YuEn-git** [comment]
main.py:

```python
from mmseg.registry import TRANSFORMS, DATASETS
from mmengine.config import Config
from LaneDataset.openlane import *
from lanetask import *


if __name__ == '__main__':
    cfg = Config.fromfile('config/temp_configs.py')
    # t = TRANSFORMS.build(cfg.transform)  
    dataset = DATASETS.build(cfg.dataset)
    datas = next(iter(dataset))
    print('a')
```



lanetask.py:

```python
from typing import Dict, List, Optional, Tuple, Union
import warnings

import numpy as np
from mmcv.transforms import to_tensor
from mmcv.transforms.base import BaseTransform
from mmengine.structures import PixelData

from mmseg.registry import TRANSFORMS

@TRANSFORMS.register_module()
class LoadLaneAnnos(BaseTransform):

    def __init__(self) -> None:
        super().__init__()
    
    def transform(self, results: Dict):
        results['extrinsic'] = np.array(results['extrinsic'], dtype=np.float32)
        results['intrinsic'] = np.array(results['intrinsic'], dtype=np.float32)
        ori_lanelines = results['lanelines']
        laneline_array = np.vstack([np.array(lane['xzv'], dtype=np.float32) for lane in ori_lanelines]) #[3*N_lane, N_points]
        cate_array = np.array([lane['category'] for lane in ori_lanelines], dtype=np.int8) #[N_lane]
        results['lanelines'] =  dict(xzv_s=laneline_array, cates=cate_array)
        return results



```

openlanedataset.py

```python
import os.path as osp
from typing import Callable, List, Optional, Sequence, Union
from mmengine.dataset import BaseDataset
from mmseg.registry import DATASETS
from mmdet.datasets.transforms import PackDetInputs

@DATASETS.register_module()
class OpenLaneDataset(BaseDataset):
    def __init__(self,
                 ann_file: Optional[str] = '',
                 metainfo: Optional[dict] = None,
                 data_root: Optional[str] = '',
                 data_prefix: dict = dict(img_path=''),
                 pipeline: List[Union[dict, Callable]] = [],
                 test_mode: bool = False,
                 **kwargs):
        # get self.data_list include each sample info(dict)
        # when call __getitem__ will send self.data_list[idx] to pipeline
        super().__init__(ann_file, metainfo, data_root, data_prefix, pipeline=pipeline, test_mode=test_mode, **kwargs)
```


temp_configs.py:

```python
custom_imports = dict(imports=['LaneDataset.openlane', 'lanetask'], allow_failed_imports=False)

# transform = dict(type='LoadImageFromFile')

# custom_imports = dict(imports=['LaneDataset.lanetask'], allow_failed_imports=False)

# custom_imports = dict(imports=['mmseg.datasets.transforms.lane3Dtask'], allow_failed_imports=False)

input_size = (360, 480)
dataset=dict(
        type='OpenLaneDataset',
        data_root='/mnt/B/LeY/OpenLane-Dataset/',
        ann_file = 'data_annotations/OpenLane_lane3d_300_training_mmtype.pkl',
        data_prefix=dict(),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadLaneAnnos'),
            dict(type='Resize', img_scale=(input_size[1], input_size[0]), keep_ratio=False),
        ])

```

**Comment by YuEn-git** [comment]
> Sorry that I cannot reproduce your error. Can you provide the full `main.py` and `lanetask.py`?

main.py:

```python
from mmseg.registry import TRANSFORMS, DATASETS
from mmengine.config import Config
from LaneDataset.openlane import *
from lanetask import *


if __name__ == '__main__':
    cfg = Config.fromfile('config/temp_configs.py')
    # t = TRANSFORMS.build(cfg.transform)  
    dataset = DATASETS.build(cfg.dataset)
    datas = next(iter(dataset))
    print('a')
```



lanetask.py:

```python
from typing import Dict, List, Optional, Tuple, Union
import warnings

import numpy as np
from mmcv.transforms import to_tensor
from mmcv.transforms.base import BaseTransform
from mmengine.structures import PixelData

from mmseg.registry import TRANSFORMS

@TRANSFORMS.register_module()
class LoadLaneAnnos(BaseTransform):

    def __init__(self) -> None:
        super().__init__()
    
    def transform(self, results: Dict):
        results['extrinsic'] = np.array(results['extrinsic'], dtype=np.float32)
        results['intrinsic'] = np.array(results['intrinsic'], dtype=np.float32)
        ori_lanelines = results['lanelines']
        laneline_array = np.vstack([np.array(lane['xzv'], dtype=np.float32) for lane in ori_lanelines]) #[3*N_lane, N_points]
        cate_array = np.array([lane['category'] for lane in ori_lanelines], dtype=np.int8) #[N_lane]
        results['lanelines'] =  dict(xzv_s=laneline_array, cates=cate_array)
        return results



```

openlanedataset.py

```python
import os.path as osp
from typing import Callable, List, Optional, Sequence, Union
from mmengine.dataset import BaseDataset
from mmseg.registry import DATASETS
from mmdet.datasets.transforms import PackDetInputs

@DATASETS.register_module()
class OpenLaneDataset(BaseDataset):
    def __init__(self,
                 ann_file: Optional[str] = '',
                 metainfo: Optional[dict] = None,
                 data_root: Optional[str] = '',
                 data_prefix: dict = dict(img_path=''),
                 pipeline: List[Union[dict, Callable]] = [],
                 test_mode: bool = False,
                 **kwargs):
        # get self.data_list include each sample info(dict)
        # when call __getitem__ will send self.data_list[idx] to pipeline
        super().__init__(ann_file, metainfo, data_root, data_prefix, pipeline=pipeline, test_mode=test_mode, **kwargs)
```


temp_configs.py:

```python
custom_imports = dict(imports=['LaneDataset.openlane', 'lanetask'], allow_failed_imports=False)

# transform = dict(type='LoadImageFromFile')

# custom_imports = dict(imports=['LaneDataset.lanetask'], allow_failed_imports=False)

# custom_imports = dict(imports=['mmseg.datasets.transforms.lane3Dtask'], allow_failed_imports=False)

input_size = (360, 480)
dataset=dict(
        type='OpenLaneDataset',
        data_root='/mnt/B/LeY/OpenLane-Dataset/',
        ann_file = 'data_annotations/OpenLane_lane3d_300_training_mmtype.pkl',
        data_prefix=dict(),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadLaneAnnos'),
            dict(type='Resize', img_scale=(input_size[1], input_size[0]), keep_ratio=False),
        ])

```

**Comment by YuEn-git** [comment]
> > Sorry that I cannot reproduce your error. Can you provide the full `main.py` and `lanetask.py`?
> 
> main.py:
> 
> ```python
> from mmseg.registry import TRANSFORMS, DATASETS
> from mmengine.config import Config
> from LaneDataset.openlane import *
> from lanetask import *
> 
> 
> if __name__ == '__main__':
>     cfg = Config.fromfile('config/temp_configs.py')
>     # t = TRANSFORMS.build(cfg.transform)  
>     dataset = DATASETS.build(cfg.dataset)
>     datas = next(iter(dataset))
>     print('a')
> ```
> 
> lanetask.py:
> 
> ```python
> from typing import Dict, List, Optional, Tuple, Union
> import warnings
> 
> import numpy as np
> from mmcv.transforms import to_tensor
> from mmcv.transforms.base import BaseTransform
> from mmengine.structures import PixelData
> 
> from mmseg.registry import TRANSFORMS
> 
> @TRANSFORMS.register_module()
> class LoadLaneAnnos(BaseTransform):
> 
>     def __init__(self) -> None:
>         super().__init__()
>     
>     def transform(self, results: Dict):
>         results['extrinsic'] = np.array(results['extrinsic'], dtype=np.float32)
>         results['intrinsic'] = np.array(results['intrinsic'], dtype=np.float32)
>         ori_lanelines = results['lanelines']
>         laneline_array = np.vstack([np.array(lane['xzv'], dtype=np.float32) for lane in ori_lanelines]) #[3*N_lane, N_points]
>         cate_array = np.array([lane['category'] for lane in ori_lanelines], dtype=np.int8) #[N_lane]
>         results['lanelines'] =  dict(xzv_s=laneline_array, cates=cate_array)
>         return results
> ```
> 
> openlanedataset.py
> 
> ```python
> import os.path as osp
> from typing import Callable, List, Optional, Sequence, Union
> from mmengine.dataset import BaseDataset
> from mmseg.registry import DATASETS
> from mmdet.datasets.transforms import PackDetInputs
> 
> @DATASETS.register_module()
> class OpenLaneDataset(BaseDataset):
>     def __init__(self,
>                  ann_file: Optional[str] = '',
>                  metainfo: Optional[dict] = None,
>                  data_root: Optional[str] = '',
>                  data_prefix: dict = dict(img_path=''),
>                  pipeline: List[Union[dict, Callable]] = [],
>                  test_mode: bool = False,
>                  **kwargs):
>         # get self.data_list include each sample info(dict)
>         # when call __getitem__ will send self.data_list[idx] to pipeline
>         super().__init__(ann_file, metainfo, data_root, data_prefix, pipeline=pipeline, test_mode=test_mode, **kwargs)
> ```
> 
> temp_configs.py:
> 
> ```python
> custom_imports = dict(imports=['LaneDataset.openlane', 'lanetask'], allow_failed_imports=False)
> 
> # transform = dict(type='LoadImageFromFile')
> 
> # custom_imports = dict(imports=['LaneDataset.lanetask'], allow_failed_imports=False)
> 
> # custom_imports = dict(imports=['mmseg.datasets.transforms.lane3Dtask'], allow_failed_imports=False)
> 
> input_size = (360, 480)
> dataset=dict(
>         type='OpenLaneDataset',
>         data_root='/mnt/B/LeY/OpenLane-Dataset/',
>         ann_file = 'data_annotations/OpenLane_lane3d_300_training_mmtype.pkl',
>         data_prefix=dict(),
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(type='LoadLaneAnnos'),
>             dict(type='Resize', img_scale=(input_size[1], input_size[0]), keep_ratio=False),
>         ])
> ```

I think I get the way to solve my bug. It can refer to https://github.com/open-mmlab/mmengine/issues/1111#issue-1684450472 and https://github.com/open-mmlab/mmengine/issues/1111#issue-1684450472
