### ISSUE TITLE
[Bug] build_optim_wrapper raise an Error

### ISSUE THREAD

**Issue by zero0kiriyu** [open-mmlab/mmengine#1323]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

mmengine dev branch
mmpretrain dev branch

### Reproduces the problem - code sample

python tools/train.py configs/spark/spark_sparse-convnext-small_16xb256-amp-coslr-800e_in1k.py

### Reproduces the problem - command or script

python tools/train.py configs/spark/spark_sparse-convnext-small_16xb256-amp-coslr-800e_in1k.py

### Reproduces the problem - error message

TypeError: None is not a callable object

### Additional information

用最新分支的mmptrain和mmengine训练的时候会提示错误，检查后发现是最新的mmengine里的逻辑有问题

https://github.com/open-mmlab/mmengine/blob/a53c2802a63f8d0c49b5c348e0d785f4feddd78a/mmengine/optim/optimizer/default_constructor.py#L301

这几行新修改的代码无法识别其他项目中注册的optimizer，导致返回None

**Comment by HAOCHENYE** [comment]
Hi~ Thanks for your feedback. Would mind checking will PR #1324  fix your problem?

**Comment by zero0kiriyu** [comment]
已解决
