### ISSUE TITLE
[Feature] Loss abstraction

### ISSUE THREAD

**Issue by AwePhD** [open-mmlab/mmengine#1399]
### What is the feature?

In `mmengine` there are a lot of abstractions. All these abstractions have a relevant design: `Runner, Loop, Dataset, Registry, BaseModule, BaseModel, DataSample` etc.. Why there is no abstraction for losses? I mean abstraction in the head models that apply the loss. 

I mostly interact with the `mmdet` framework, and I can see that loss should be hard coded in the detection head when performing the implementation without any base interface - there is no `loss, predict, _forward` in head model.  There is no abstraction / metaclass for the head component that would apply a list of losses, set in attribute `losses`. Usually the same loss process is applied: `multi_apply` on all outputs that are concerned by a loss and apply the loss.  For example, in detection task there is `loss, loss_by_feat, loss_by_feat_single` in almost all heads.

So this "feature request" is mostly a question why there is no loss abstraction. I guess the mmlab team already thought about it since the design of mmlab is clean. I might miss the big picture view to see a loss interface in head component would not generalize well to all the needs of the mmlab suite. Plus, in `mmlab` v1 there was a `LOSS` registry that got merge with `MODEL` registry.

Thanks for you time and attention.

**Comment by HAOCHENYE** [comment]
The primary reason for not designing a dedicated abstraction for Loss is that the process of calculating Loss (not just in mmdet) is mostly uncontrollable. Where to calculate the loss, how many times to calculate it, the order of the loss, and so on, vary significantly across different tasks. It's challenging to summarize a unified process and subsequently abstract a consistent interface.

**Comment by AwePhD** [comment]
Okay, thank you for your explanation, very much appreciated!
