### ISSUE TITLE
[Bug] OneCycleLR object has no attribute 'end',(use before super().__init__())

### ISSUE THREAD

**Issue by whlook** [open-mmlab/mmengine#1401]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

obvious code bug
bug code: https://github.com/open-mmlab/mmengine/blob/c65187c6b8a9b055e44136f0ee71da3c658b42f5/mmengine/optim/scheduler/param_scheduler.py#L987

### Reproduces the problem - code sample

# learning policy                           
param_scheduler = [                         
    dict(                                   
        type="OneCycleLR",                  
        eta_max=2e-4,                       
        pct_start=0.3,      
        div_factor=50,    
        final_div_factor=1e3, 
    )                                       
]                                           
                                            

### Reproduces the problem - command or script

None

### Reproduces the problem - error message

<pre>AttributeError: &apos;OneCycleLR&apos; object has no attribute &apos;end&apos;</pre>

### Additional information

Param `end` supports default value, but in `OneCycleLR`'s __init__, it use self.end before doing super().__init__() // self.end was defined in Base class.

suggestion: 
1. do super.__init__ at the beginning.  Or
2. Use `end - start` but not `self.end - self.start`

**Comment by zhouzaida** [comment]
Hi @whlook, thanks for your report and your modification suggestions. I prefer the second suggestion. 
Are you interested in making a PR to fix this issue?
