### ISSUE TITLE
怎么调用ProfilerHook

### ISSUE THREAD

**Issue by ChaoyiXie** [open-mmlab/mmengine#1442]
### What is the feature?

如何调用ProfilerHook去实现训练时对CPU，GPU，内存等情况的可视化，debug mmengine相比于mmcv训练时长更慢的原因

**Comment by zhouzaida** [comment]
你好，可以参考 https://mmengine.readthedocs.io/zh-cn/latest/tutorials/hook.html#profilerhook。
