### ISSUE TITLE
[Feature] 保存的pth文件越来越大

### ISSUE THREAD

**Issue by ChaoyiXie** [open-mmlab/mmengine#1446]
### What is the feature?

我设置的CheckpointHook参数如下：
checkpoint=dict(
        type='CheckpointHook',
        interval=1,
        save_optimizer=True,
        by_epoch=True,
        max_keep_ckpts=200,
    )
保存的pth文件越来越大是怎么回事，我用的是mmengine0.9.1版本，pytorch是1.10.1

**Comment by HAOCHENYE** [comment]
因为 ckpt 里会保存历史的 lr、loss 等历史信息。

**Comment by zhouzaida** [comment]
@ChaoyiXie 可以设置 save_optimizer=False 和 save_param_scheduler=False，这样 ckpt 就会小很多，但如果训练中断了，是不能正常 resume 的，因为 ckpt 中没有保存 optimizer 和 param scheduler 的信息
