### ISSUE TITLE
scattering the data to gpu when using base dataelement

### ISSUE THREAD

**Issue by ajaynitk** [open-mmlab/mmengine#1501]
### What is the feature?

It is convenient if we have support for scattering data to gpus's when using base data element like we have for data container in the previous open mmlab versions.

**Comment by zhouzaida** [comment]
Hi, you can use the cuda method.

https://github.com/open-mmlab/mmengine/blob/9b984056726583f9bafcfb35daad0e4feb97cab9/mmengine/structures/base_data_element.py#L503
