### ISSUE TITLE
Is anywhere record the version support matrix between mmengine and pytorch?

### ISSUE THREAD

**Issue by kelvinwang139** [open-mmlab/mmengine#1509]
### 📚 The doc issue

Is anywhere record the version support matrix between mmengine and pytorch?

**Comment by zhouzaida** [comment]
Hi @kelvinwang139 , we did not provide this matrix but it is a good proposal and we will provide soon. BTW, mmengine supports pytorch>=1.6 and pytorch<=2.1.0.

**Comment by kelvinwang139** [comment]
> Hi @kelvinwang139 , we did not provide this matrix but it is a good proposal and we will provide soon. BTW, mmengine supports pytorch>=1.6 and pytorch<=2.1.0.

Thanks for your nice response！
