### ISSUE TITLE
[Feature] 训练得到的权重命名问题

### ISSUE THREAD

**Issue by anzitong** [open-mmlab/mmengine#1545]
### What is the feature?

如果我需要使得生成的模型权重文件命名方式为‘’模型名-数据集名-epoch数量-时间‘’我应该怎么做？

**Comment by zhouzaida** [comment]
可以设置 CheckpointHook 中的 filename_tmpl 参数，https://github.com/open-mmlab/mmengine/blob/66fb81f7b392b2cd304fc1979d8af3cc71a011f5/mmengine/hooks/checkpoint_hook.py#L81

如果你不清楚如何配置 filename_tmpl 参数，可以参考 https://mmengine.readthedocs.io/zh-cn/latest/tutorials/hook.html#checkpointhook

**Comment by anzitong** [comment]
非常感谢
