### ISSUE TITLE
ValueError when use `--resume` because of the dataset meta comparsion

### ISSUE THREAD

**Issue by liqikai9** [open-mmlab/mmengine#438]
When I used `--resume` in `tools/train.py`, the program will check whether the dataset meta in the loaded checkpoint file and the dataset meta built from the config are the same, like the code here:

https://github.com/open-mmlab/mmengine/blob/ac8686e28bb7285fe9d8fcd97e588406d4a6f164/mmengine/runner/runner.py#L1920

But when my dataset contains some type that is not Python-builtin type, like numpy.ndarray, the comparison function will raise the following error:

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
    and dataset_meta != self.train_dataloader.dataset.metainfo):
```

Do you have any solution for this? Thanks~

**Comment by HAOCHENYE** [comment]
Solved in #511
