### ISSUE TITLE
detect_anomalous_params cannot be setting

### ISSUE THREAD

**Issue by BIGWangYuDong** [open-mmlab/mmengine#454]
The DDP cannot set `detect_anomalous_params`

https://github.com/open-mmlab/mmengine/blob/ec72f59bf3e57c124a9cb68258f2faf7a94be712/mmengine/runner/runner.py#L845-L866

Also, maybe we can add a warning to tell users that it will slow down the training speed, and suggest only used in debugging.

**Comment by ZwwWayne** [comment]
Please paste your trial and the error/unexpected results.

**Comment by zhouzaida** [comment]
```python
model_wrapper_cfg = {
    'type': 'MMDistributedDataParallel',
    'detect_anomalous_params': True,
}
```
