### ISSUE TITLE
Rendering issue of markdown docs

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmengine#486]
```suggestion
`MMEngine` 实现了一套统一的文件读写接口，可以用同一个函数来处理不同的文件格式，如 `json`、
`yaml` 和 `pickle`，并且可以方便地拓展其它的文件格式。除此之外，文件读写模块还支持从多种文件存储后端读写文件，包括本地磁盘、Petrel（内部使用）、Memcached、LMDB 和 HTTP。
```
github的markdown渲染器似乎因为这个换行而多渲染出来一个空格。下面也有很多类似这样的情况。是否需要修一下？

_Originally posted by @C1rN09 in https://github.com/open-mmlab/mmengine/pull/420#discussion_r957027469_

**Comment by C1rN09** [comment]
Actually, this is not an issue of markdown, but of HTML. Therefore it influences [ReadtheDocs](https://mmengine.readthedocs.io/zh_CN/latest/advanced_tutorials/fileio.html) as well. This [post](https://stackoverflow.com/questions/8550112/prevent-workaround-browser-converting-n-between-lines-into-space-for-chinese/8551033#8551033) describes the historical reason behind this issue. For short, HTML specification treats `end of line` as a `white space`, which is reasonable for English and other Western European languages, but **NOT** for Chinese.

Currently it seems HTML has no plan to fix this issue. I suggest we make it a specification in our project, that any natural paragraph in Chinese documentations should not be split into 2 paragraphs by end of line characters. We may further enforce it by adding a pre-commit-hook.
