### ISSUE TITLE
How to access dataset in train_step

### ISSUE THREAD

**Issue by CSU-NXY** [open-mmlab/mmengine#561]
Hi, thank you for your great framework.

I have some universal data stored in my dataset, which is quite large and useful during training. When using `IterBasedTrainLoop` to train my model, is there any methods to access these data in `model.train_step` other than put it into every `data_batch`?

Thank you very much!

**Comment by HAOCHENYE** [comment]
HI! Sorry for my late reply (we were on vacation before :rofl:). If you want to access dataset in `train_step`. You can store a reference of your dataset in `runner.message_hub`, which can be accessed globally:

```python
MessageHub.get_current_instance().update_info('dataset', dataset)
```

And then you can access your dataset anywhere by:
```python
dataset = MessageHub.get_current_instance().get_info('dataset')
```

**Comment by CSU-NXY** [comment]
Thanks very much, you really saved the day!
