### ISSUE TITLE
[Feature Request] Make it simpler to use custom dist backend

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmengine#567]
**Describe the feature**

I'd like a simple way to use a custom torch distributed backend without needing to modify MMEngine source code and install as a dev package.

**Motivation**

I'd like to use the SMDDP backend because it is faster than standard DDP on AWS, however, I'm not sure how to add my own backend.

**Related resources**

Here is the documentation for using SMDDP with PyTorch: https://sagemaker.readthedocs.io/en/stable/api/training/sdp_versions/latest/smd_data_parallel_pytorch.html

It's very simple to use:

```python
import smdistributed.dataparallel.torch.torch_smddp
import torch.distributed as dist

dist.init_process_group(backend='smddp')
```

**Additional context**

The `smdistributed` library is not available via PyPi. It comes preinstalled in [Amazon's DLC](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#sagemaker-framework-containers-sm-support-only)'s [deep learning containers, prebuilt docker images]). So

**Comment by zhouzaida** [comment]
Hi @austinmw , there are two ways to satisfy the requirement. One way is to overwrite the `setup_env` method of `Runner`. Another is to modify the implementation of `init_dist`. Do you have any better ways to do it?

**Comment by austinmw** [comment]
Hi @zhouzaida Thanks for your help. I'm trying to brainstorm ways to prevent needing to edit MMEngine and therefore rebuild my training docker container to turn this backend on or off. Maybe one way could be something like:

`train.py --custom_dist_init /path/to/init_smddp.py`

`init_smddp.py`:

```python
import smdistributed.dataparallel.torch.torch_smddp
import torch.distributed as dist

dist.init_process_group(backend='smddp')
```

**Comment by zhouzaida** [comment]
The method you provided is more flexible and does not require modification of the mmengine source code, but considering that users do not often customize init_dist, can we directly modify the init_dist function, and users are free to choose the desired method through the runner's env_cfg parameter.

https://github.com/open-mmlab/mmengine/blob/36af1f0fee811352369a26d27bd372eb54b6b6ea/mmengine/runner/runner.py#L258

**Comment by austinmw** [comment]
Yeah that sounds reasonable to me. 

I tried quickly doing:
1. Add the cfg-option `env_cfg.dist_cfg.backend'='smddp'`
2. Add import in mmdet `train.py` of `import smdistributed.dataparallel.torch.torch_smddp`
3. Use `--launcher='mpi'` 
4. Then launch like this:

```bash
mpirun --host algo-1-mghgy -np 4 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 1 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_SINGLENODE=1 -x FI_PROVIDER=efa -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.8/site-packages/gethostname.cpython-38-x86_64-linux-gnu.so -verbose -x NCCL_DEBUG=VERSION smddprun /opt/conda/bin/python3.8 -m mpi4py sagemaker_train.py --config /opt/ml/code/configs/yolox/yolox_s_8xb8-300e_coco.py --work-dir /opt/ml/checkpoints
```

However when I do this I get:

```
atonk859kl-algo-1-mghgy | [1,mpirank:0,algo-1]<stdout>:NCCL version 2.10.3+cuda11.3
atonk859kl-algo-1-mghgy | [1,mpirank:0,algo-1]<stdout>:Running smdistributed.dataparallel v1.5.1
atonk859kl-algo-1-mghgy | [1,mpirank:0,algo-1]<stdout>:SMDDP: Single node mode
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:smddp: broadcast called for tensor with default device index (-1), assuming local_rank locality.
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:Traceback (most recent call last):
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    return _run_code(code, main_globals, None,
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    exec(code, run_globals)
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    main()
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/site-packages/mpi4py/run.py", line 198, in main
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    run_command_line(args)
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    run_path(sys.argv[0], run_name='__main__')
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    return _run_module_code(code, init_globals, run_name,
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    _run_code(code, mod_globals, init_globals,
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    exec(code, run_globals)
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "sagemaker_train.py", line 158, in <module>
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    main()
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "sagemaker_train.py", line 147, in main
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    runner = Runner.from_cfg(cfg)
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 433, in from_cfg
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    runner = cls(
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 347, in __init__
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    self.setup_env(env_cfg)
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 652, in setup_env
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    broadcast(timestamp)
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/dist/dist.py", line 310, in broadcast
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    torch_dist.broadcast(data_on_device, src, group)
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:    work = default_pg.broadcast([tensor], opts)
atonk859kl-algo-1-mghgy | [1,mpirank:1,algo-1]<stdout>:ValueError: Expected devices to have indices, got cpu
atonk859kl-algo-1-mghgy | --------------------------------------------------------------------------
atonk859kl-algo-1-mghgy | MPI_ABORT was invoked on rank 1 in communicator MPI COMMUNICATOR 4 DUP FROM 0
atonk859kl-algo-1-mghgy | with errorcode 1.
```

I'm not sure what this error is. I'll try to reach out to SMDDP team as well.

**Comment by zhouzaida** [comment]
According to the error message, we can see that the initialization of the distributed environment was successful, as it entered  this block.

https://github.com/open-mmlab/mmengine/blob/36af1f0fee811352369a26d27bd372eb54b6b6ea/mmengine/dist/dist.py#L302-L310.

The error should be caused by `get_comm_device` function.

https://github.com/open-mmlab/mmengine/blob/36af1f0fee811352369a26d27bd372eb54b6b6ea/mmengine/dist/utils.py#L421-L438

**Comment by austinmw** [comment]
Worked, thanks! Want me to submit a PR?

https://github.com/austinmw/mmengine/blob/826562285b4c0f33dbe219e9a8d5b71b4b250d85/mmengine/dist/utils.py#L110-L133

https://github.com/austinmw/mmengine/blob/826562285b4c0f33dbe219e9a8d5b71b4b250d85/mmengine/dist/utils.py#L43-L64

https://github.com/austinmw/mmengine/blob/826562285b4c0f33dbe219e9a8d5b71b4b250d85/mmengine/dist/utils.py#L447-L466

----

By the way I also needed to change MMDetection's `train.py` a bit in order for this to work in SageMaker. In particular:
https://github.com/open-mmlab/mmdetection/blob/9d3e162459590eee4cfc891218dfbb5878378842/tools/train.py#L94-L95

to:
```python
    if 'LOCAL_RANK' not in os.environ:
        if args.launcher in ['mpi', 'smddp']:
            os.environ['LOCAL_RANK'] = str(os.environ['OMPI_COMM_WORLD_LOCAL_RANK'])
        else:
            os.environ['LOCAL_RANK'] = str(args.local_rank)
```
But I can create an issue thread there and maybe submit a PR like `tools/sagemaker_train.py`

**Comment by zhouzaida** [comment]
Cool. It would be great if you could submit a PR to support SageMaker.

BTW, can we set the environment `LOCAL_RANK` in `_init_dist_mpi` that does not need to modify the source code of mmdetection?

**Comment by austinmw** [comment]
@zhouzaida Actually it looks like once I switched to placing this inside `_init_dist_mpi` I no longer needed to make any modifications to `LOCAL_RANK`.

Here's my PR: https://github.com/open-mmlab/mmengine/pull/579

Seems to train successfully on SageMaker for me. I use a custom docker image if anyone interested in testing:

```Dockerfile
# Use Sagemaker PyTorch container as base image
ARG REGION
FROM 763104351884.dkr.ecr.${REGION}.amazonaws.com/pytorch-training:1.12.0-gpu-py38-cu113-ubuntu20.04-sagemaker

# Set the path for MMDetection
ENV MMDETECTION /opt/mmdetection

# Install MMEngine, MMCV, MMDetection
WORKDIR /opt/ml/code
RUN pip install cython && \
    pip install -U openmim && \
    pip install git+https://github.com/austinmw/mmengine.git@smddp && \
    mim install "mmcv>=2.0.0rc1" -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12.0/index.html && \
    pip install -U tensorboard torch-model-archiver && \
    cd /opt; git clone -b v3.0.0rc2 https://github.com/austinmw/mmdetection.git && \
    cd mmdetection; pip install -e . && \
    pip install -U git+https://github.com/awslabs/sagemaker-debugger.git@1.0.22 && \
    rm -rf /var/lib/apt/lists/*

# Configure ENVs
ENV SM_LOG_LEVEL 30
ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code
ENV MMDETECTION /opt/mmdetection
# Add ENV's to address https://github.com/pytorch/pytorch/issues/37377
ENV MKL_THREADING_LAYER GNU
ENV MKL_NUM_THREADS 8
ENV OMP_NUM_THREADS 8

WORKDIR /
```
