### ISSUE TITLE
registry issue

### ISSUE THREAD

**Issue by Tony-Hou** [open-mmlab/mmengine#568]
mmengine 中的注册registry 装饰器为什么要设计成每次手动 register_module() 的形式，为什么不在registry类中添加__call__()函数来解决每次手动注册的问题

**Comment by zhouzaida** [comment]
你好，Registry 实现 `__call__` 方法并调用 `register_module` 同样也可以实现注册功能，但直接调用 `register_module` 会更直观一点。下面是两种用法的对比。

```python
MODEL = Registry('model')

@MODEL()
class ToyModel(nn.Module):
    pass

@MODEL.register_module()
class ToyModel(nn.Module):
    pass
```

**Comment by zhouzaida** [comment]
这类问题我们可以在 https://github.com/open-mmlab/mmengine/discussions/554 有更多的讨论
