### ISSUE TITLE
[Feature Request] PyTorch Profiler With TensorBoard

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmengine#581]
**Describe the feature**

TensorBoard plugin with PyTorch Profiler

https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html

**Motivation**

This is a really great profiler option. I've used it with a lot of success in PyTorch Lightning since they've added it. I know from the migration docs that the profiler is not yet available, but when it becomes available this would be a great addition.

**Related resources**

Would really encourage anyone who hasn't already seen this to take a look at:
https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html

**Comment by zhouzaida** [comment]
Hi @austinmw , this future will be supported this month or next month.

**Comment by austinmw** [comment]
Awesome!
