### ISSUE TITLE
ETA information disappears when iter num smaller than window_size

### ISSUE THREAD

**Issue by Tau-J** [open-mmlab/mmengine#582]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmengine.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

If the number of iterations per epoch is smaller than `window_size`(defaults to 50), there will be no `eta` in training logs. I'm quite sure this bug caused by this line: 

https://github.com/open-mmlab/mmengine/blob/26e5462447dbc0c5b1b9e2b313cc28a5d4bc4dd9/mmengine/hooks/iter_timer_hook.py#L89

but I think the best solution is to set `window_size=min(window_size, num_batch)` when parsing config files.

**Comment by HAOCHENYE** [comment]
#508 has solved this issue.
