### ISSUE TITLE
Does mmengine implement the early stopping?

### ISSUE THREAD

**Issue by RlChen0** [open-mmlab/mmengine#597]
I saw mmengine support early stopping in the docs，but can’t find any instruction about it.

**Comment by zhouzaida** [comment]
Hi @RlChen0 , mmengine does not support early stopping now but we have a plan to support it.

**Comment by MiXaiLL76** [comment]
@zhouzaida any update?

Do you have plans to make your own implementation - or port someone else's?

If there is some kind of plan, but there are not enough hands, I think it is worth discussing and someone will take this job

**Comment by zhouzaida** [comment]
Hi @MiXaiLL76 , #739 will support EarlyStoppingHook.

**Comment by zhouzaida** [comment]
This issue is a duplicate of another issue, please discuss it under that issue #356.
