### ISSUE TITLE
[Feature Request] Log hook info

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmengine#599]
**Describe the feature**

I really liked the feature that was in MMCV v1.x to log the hook order:
https://github.com/open-mmlab/mmcv/blob/3dd2a21b45b6303b8202f89de4ebb0f52731e4dd/mmcv/runner/epoch_based_runner.py#L113

Can this be added to MMEngine?

**Motivation**
This helps to ensure you understand and have a log of what's being ran when you kick off training

**Comment by zhouzaida** [comment]
Hi @austinmw , we will add this feature to MMEngine ASAP.

**Comment by songyuc** [comment]
Thanks for the suggestion and the guide from @HAOCHENYE.
I notices that current [mmengine.Runner](https://github.com/open-mmlab/mmengine/blob/main/mmengine/runner/runner.py#L58-L59) missed a `get_hook_info()` method, and I don't know whether a direct copy from MMCVv1.x would work.

### Get_hook_info()
**MMCVv1.x: BaseRunner.get_hook_info()**
https://github.com/open-mmlab/mmcv/blob/3dd2a21b45b6303b8202f89de4ebb0f52731e4dd/mmcv/runner/base_runner.py#L319-L340
**MMEngine: Runner.hooks**
https://github.com/open-mmlab/mmengine/blob/main/mmengine/runner/runner.py#L550-L553

### Point proposal
**MMCVv1.x: before ` self.call_hook('before_run')` and epoch-while in mmcv.EpochBasedRunner.run()**
https://github.com/open-mmlab/mmcv/blob/3dd2a21b45b6303b8202f89de4ebb0f52731e4dd/mmcv/runner/epoch_based_runner.py#L113-L119
**MMEngine: before `self.call_hook('before_run')` in mmengine.Runner.train()**
https://github.com/open-mmlab/mmengine/blob/main/mmengine/runner/runner.py#L1645-L1646

**Comment by songyuc** [comment]
Hi, @zhouzaida, I have written a test function like:
```python
    def test_get_hooks_info(self):
        # test get_hooks_info() function
        cfg = copy.deepcopy(self.epoch_based_cfg)
        cfg.experiment_name = 'test_get_hooks_info1'
        cfg.runner_type = 'CustomRunner'
        runner = RUNNERS.build(cfg)
        assert isinstance(runner, CustomRunner)
        runner.logger.info('Hooks will be executed in the following order:\n%s',
                         self.get_hook_info())
```
, which is in `tests/test_runner/test_runner.py`. 
Since I have little experience about "unit test", how I can run this test function and check the results?

**Comment by HAOCHENYE** [comment]
> Hi, @zhouzaida, I have written a test script like:
> 
> ```python
> import copy
> import tempfile
> 
> from mmengine.config import Config
> from mmengine.registry import (RUNNERS, MODELS)
> from mmengine.runner import (Runner)
> 
> 
> @MODELS.register_module()
> class ResNet:
>     def __init__(self, depth, stages=4):
>         self.depth = depth
>         self.stages = stages
> 
> 
> cfg = dict(type='ResNet', depth=50)
> 
> 
> @RUNNERS.register_module()
> class CustomRunner(Runner):
> 
>     def __init__(self,
>                  model,
>                  work_dir,
>                  train_dataloader=None,
>                  val_dataloader=None,
>                  test_dataloader=None,
>                  train_cfg=None,
>                  val_cfg=None,
>                  test_cfg=None,
>                  auto_scale_lr=None,
>                  optim_wrapper=None,
>                  param_scheduler=None,
>                  val_evaluator=None,
>                  test_evaluator=None,
>                  default_hooks=None,
>                  custom_hooks=None,
>                  data_preprocessor=None,
>                  load_from=None,
>                  resume=False,
>                  launcher='none',
>                  env_cfg=dict(dist_cfg=dict(backend='nccl')),
>                  log_processor=None,
>                  log_level='INFO',
>                  visualizer=None,
>                  default_scope=None,
>                  randomness=dict(seed=None),
>                  experiment_name=None,
>                  cfg=None):
>         super(CustomRunner, self).__init__(model=model, work_dir=work_dir)
> 
>     # def setup_env(self, env_cfg):
>     #     pass
> 
> 
> def test_get_hooks_info():
>     # test get_hooks_info() function
>     temp_dir = tempfile.mkdtemp()
>     epoch_based_cfg = dict(
>         model=dict(type='ResNet', depth=50),
>         work_dir=temp_dir,
>         train_dataloader=dict(
>             dataset=dict(type='ToyDataset'),
>             sampler=dict(type='DefaultSampler', shuffle=True),
>             batch_size=3,
>             num_workers=0),
>         val_dataloader=dict(
>             dataset=dict(type='ToyDataset'),
>             sampler=dict(type='DefaultSampler', shuffle=False),
>             batch_size=3,
>             num_workers=0),
>         test_dataloader=dict(
>             dataset=dict(type='ToyDataset'),
>             sampler=dict(type='DefaultSampler', shuffle=False),
>             batch_size=3,
>             num_workers=0),
>         auto_scale_lr=dict(base_batch_size=16, enable=False),
>         optim_wrapper=dict(
>             type='OptimWrapper', optimizer=dict(type='SGD', lr=0.01)),
>         param_scheduler=dict(type='MultiStepLR', milestones=[1, 2]),
>         val_evaluator=dict(type='ToyMetric1'),
>         test_evaluator=dict(type='ToyMetric1'),
>         train_cfg=dict(
>             by_epoch=True, max_epochs=3, val_interval=1, val_begin=1),
>         val_cfg=dict(),
>         test_cfg=dict(),
>         custom_hooks=[],
>         default_hooks=dict(
>             runtime_info=dict(type='RuntimeInfoHook'),
>             timer=dict(type='IterTimerHook'),
>             logger=dict(type='LoggerHook'),
>             param_scheduler=dict(type='ParamSchedulerHook'),
>             checkpoint=dict(
>                 type='CheckpointHook', interval=1, by_epoch=True),
>             sampler_seed=dict(type='DistSamplerSeedHook')),
>         data_preprocessor=None,
>         launcher='none',
>         env_cfg=dict(dist_cfg=dict(backend='nccl')),
>     )
>     epoch_based_cfg = Config(epoch_based_cfg)
>     cfg = copy.deepcopy(epoch_based_cfg)
>     cfg.experiment_name = 'test_get_hooks_info1'
>     cfg.runner_type = 'CustomRunner'
>     runner = RUNNERS.build(cfg)
>     assert isinstance(runner, CustomRunner)
>     print('Hooks will be executed in the following order:\n%s',
>           runner.get_hook_info())
> 
> 
> if __name__ == '__main__':
>     test_get_hooks_info()
> ```
> 
> Are this setting right enough to test?

Hi, thanks for your contributions! you can post a PR first, and then we can discuss the details there.
