### ISSUE TITLE
[bug] error when using `python tools/train.py` to train `ReDet` in MMRotate.

### ISSUE THREAD

**Issue by zytx121** [open-mmlab/mmengine#638]
when the `self.distributed` equals to False, `revert_sync_batchnorm` function cannot work normally. 
https://github.com/open-mmlab/mmengine/blob/bda92b49e751c721c11bb15623dabc7f7a9517e7/mmengine/runner/runner.py#L848

We argue this is caused by [ReDet](https://github.com/open-mmlab/mmrotate/blob/dev-1.x/configs/redet/redet_re50_refpn_1x_dota_le90.py) replacing ``torch.nn`` with ``e2cnn.nn``.

https://github.com/open-mmlab/mmrotate/blob/dev-1.x/mmrotate/models/backbones/re_resnet.py

**Comment by HAOCHENYE** [comment]
Can you provide a more detailed description of the error? Does `revert_sync_batchnorm` raise an error or not convert the `SyncBN` to `BN`?

**Comment by zytx121** [comment]
![1667186839276](https://user-images.githubusercontent.com/10410257/198924981-6b78d56c-49ee-4507-8206-76dc1cfddcd4.png)

Yes, `revert_sync_batchnorm` raises an error when converting the `SyncBN` to `BN`.  However,  there is no `SyncBatchNorm` module in e2cnn. The error occurs by the `add_module` function. In e2cnn, `R2Conv` is the smallest unit, which cannot be splitter. When we try to get `R2Conv` by `add_module`,  this [line](https://github.com/QUVA-Lab/e2cnn/blob/d8128366f07630059b669bdcba90ce625de06c8f/e2cnn/nn/modules/sequential_module.py#L97) raise an error.

Maybe,  we need to allow user close `revert_sync_batchnorm`.

**Comment by HAOCHENYE** [comment]
It makes sense to me. I'll add an option to the `Runner` to disable `revert_sync_batchnorm`.

**Comment by zytx121** [comment]
> It makes sense to me. Will it be more proper to fallback not revert `SyncBN` if `revert_sync_batchnorm` failed?

Nice idea.
