### ISSUE TITLE
error when using print_config.py to print config in windows

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmengine#647]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmengine.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
This should be caused by default encoding issue in windows.(gbk)
This problem will occur if there is Chinese in the configuration in windows system. ( if you run train.py you will meet the same error)
I think the system type should be consider when reading and writing files(like config)

**1. What command or script did you run?**
[
![微信图片_20221028212200](https://user-images.githubusercontent.com/96160062/198608622-28473cb6-73b0-46e9-a366-2a257cfccb82.jpg)
](url)

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Windows10**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

(mmdet) PS D:\github\mmdetection> python mmdet/utils/collect_env.py
sys.platform: win32
Python: 3.8.13 (default, Oct 19 2022, 22:38:03) [MSC v.1916 64 bit (AMD64)]
CUDA available: False
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31630 版
GCC: n/a
PyTorch: 1.13.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.0
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: MSVC 193331630
MMCV CUDA Compiler: not available
MMDetection: 2.25.3+e71b499
(mmdet) PS D:\github\mmdetection> 

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by HAOCHENYE** [comment]
Hi! thanks for your contribution, it seems there is an encoding compatibility issue when exporting Config on Windows. Would mind posting a PR to solve this problem :smile: ? If it is not convenient for you, we'll fix it ASAP.

**Comment by sanbuphy** [comment]
> 

OK, ：I'm just worried that I fixed it but it doesn't conform the specification.（generalized） But I will try to post a PR.
