### ISSUE TITLE
[B4]构建模型报错：TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

### ISSUE THREAD

**Issue by Gaofan666** [open-mmlab/mmengine#649]
![f97c648c972b16f7994f5f80bac8579](https://user-images.githubusercontent.com/60742877/198768866-16701edc-3395-40cf-8b64-4f49655ec9b7.jpg)

**Comment by HAOCHENYE** [comment]
Hi, it seems there are some problems with your annotation file, can you load it by `json` manually?

**Comment by Gaofan666** [comment]
thank u for your advice , its cause the jsonfile is None, i have solved this it by reload the coco_tiny dataset
