### ISSUE TITLE
support Adan

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmengine#652]
support  adan

https://arxiv.org/pdf/2208.06677.pdf
https://github.com/sail-sg/Adan

![image](https://user-images.githubusercontent.com/25839884/198944391-abb4f3da-0496-4568-994c-1b1921f9317b.png)

**Comment by HAOCHENYE** [comment]
We consider supporting it in MMEngine 0.4.0 😃 (not later than 0.5.0 🤣 ).

**Comment by Sqhttwl** [comment]
mmengine真效率，更快更高效的优化器

**Comment by zhouzaida** [comment]
Adan has been implemented in MMCls and it will not be supported in MMEngine currently.

https://github.com/open-mmlab/mmclassification/blob/9038c1c25516c20f144d4cfa267890d9562267f2/mmcls/engine/optimizers/adan_t.py#L26
