### ISSUE TITLE
total loss is not at end

### ISSUE THREAD

**Issue by BIGWangYuDong** [open-mmlab/mmengine#660]
![pikibTTPkc](https://user-images.githubusercontent.com/48282753/199278286-9c7d8f12-6d2c-40da-95a5-459aa6696bcd.png)
After upgrade the mmengine, I found that the total loss is not at the end of the current log. Total loss at the end of the log is easier to find.

**Comment by C1rN09** [comment]
Let's invite @HAOCHENYE to have a look
