### ISSUE TITLE
How can i make [modules_statistic_results.json]  only print the registry used in config?

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmengine#667]
`modules_statistic_results.json`  made by `mmengine/registry/utils.py` `count_registered_modules`,It just print the all maintained dict(`_registry.module_dict`).
But i want to get the registry which is only used in my config, how can i do that?

**Comment by RangiLyu** [comment]
modules_statistic_results is used for counting all of the modules. If you want to print the modules used in the config, you can set log level to DEBUG by adding `log_level = 'DEBUG'`. The registry will log the information of the used modules.

**Comment by sanbuphy** [comment]
> modules_statistic_results is used for counting all of the modules. If you want to print the modules used in the config, you can set log level to DEBUG by adding `log_level = 'DEBUG'` in your config. The registry will log the information of the used modules.

Yes,I want this, Thank you so much.
