### ISSUE TITLE
could we add get_current_instance in bulid method？

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmengine#673]
I think it's trouble to deal with each error when i build something repetitive.(then I use get_current_instance).
If we can design a option in build（build from cfg）if we have built the registry, we choose True and then we get the current instance. We don’t need to use get method.

**Comment by HAOCHENYE** [comment]
Thanks for your feedback. Do you mean that [`get_instance`](https://github.com/open-mmlab/mmengine/blob/ce7d742407b8ece2afdff7dc09c9ad9f680cf35a/mmengine/utils/manager.py#L80) will throw an error if the instance with the same `name` has been created? I may not fully understand the case you described, could you please give a simple example to help me understand it?

**Comment by sanbuphy** [comment]
> Thanks for your feedback. Do you mean that [`get_instance`](https://github.com/open-mmlab/mmengine/blob/ce7d742407b8ece2afdff7dc09c9ad9f680cf35a/mmengine/utils/manager.py#L80) will throw an error if the instance with the same `name` has been created? I may not fully understand the case you described, could you please give a simple example to help me understand it?

For example,we try to build a visualizer:
> from mmdet.registry import VISUALIZERS
> visualizer = VISUALIZERS.build(model.cfg.visualizer)
> visualizer.dataset_meta = model.dataset_meta

now we have the instance of `model.cfg.visualizer`,If we use `visualizer = VISUALIZERS.build(model.cfg.visualizer)` again, we will meet wrong:class `DetLocalVisualizer` in mmdet/visualization/local_visualizer.py: <class 'mmdet.visualization.local_visualizer.DetLocalVisualizer'> instance named of visualizer has been created, the method `get_instance` should not access any other arguments.
In this case,we should use `visualizer_now = Visualizer.get_current_instance()` to get the instance.

But i think if we add some option in build（build from cfg) like:
`visualizer = VISUALIZERS.build(model.cfg.visualizer, get_instance = True)`
Although the visualizer repeatedly created,we will get the instance instead of throwing an exception.We don't need to use `get_current_instance`
If we choose False
`visualizer = VISUALIZERS.build(model.cfg.visualizer, get_instance = False)`
it will throw the `DetLocalVisualizer` exception.

**Comment by HAOCHENYE** [comment]
> > Thanks for your feedback. Do you mean that [`get_instance`](https://github.com/open-mmlab/mmengine/blob/ce7d742407b8ece2afdff7dc09c9ad9f680cf35a/mmengine/utils/manager.py#L80) will throw an error if the instance with the same `name` has been created? I may not fully understand the case you described, could you please give a simple example to help me understand it?
> 
> For example,we try to build a visualizer:
> 
> > from mmdet.registry import VISUALIZERS
> > visualizer = VISUALIZERS.build(model.cfg.visualizer)
> > visualizer.dataset_meta = model.dataset_meta
> 
> now we have the instance of `model.cfg.visualizer`,If we use `visualizer = VISUALIZERS.build(model.cfg.visualizer)` again, we will meet wrong:
> 
> ```
> class `DetLocalVisualizer` in mmdet/visualization/local_visualizer.py: <class 'mmdet.visualization.local_visualizer.DetLocalVisualizer'> instance named of visualizer has been created, the method `get_instance` should not access any other arguments.
> In this case,we should use `visualizer_now = Visualizer.get_current_instance()` to get the instance.
> ```
> 
> But i think if we add some option in build（build from cfg) like: `visualizer = VISUALIZERS.build(model.cfg.visualizer, get_instance = True)` Although the visualizer repeatedly created,we will get the instance instead of throwing an exception.We don't need to use `get_current_instance`.
> 
> If we choose False: `visualizer = VISUALIZERS.build(model.cfg.visualizer, get_instance = False)` it will throw the `DetLocalVisualizer` exception.

Got it. I think the core issue is that should we build a globally accessible instance with the same name repeatedly:

- Visualizer inherits from `ManagerMixin`, and can be accessed anywhere by calling `get_instance` or `get_current_instance` method. Since global instance is very dangerous in programming, each `Visualizer` instance has a unique name, and we should not build a visualizer instance with the same name. This is why we could not call `Visualizer.get_instance` with constructing parameters repeatedly(If you call `get_instance` only with the argument `name`, it can return a pre-built Visualizer instance).

- `build_from_cfg` is a build function for general classes, it should not involve too much class-relevant logic. Although there is still some code coupled with `ManagerMixin` like 
https://github.com/open-mmlab/mmengine/blob/ce7d742407b8ece2afdff7dc09c9ad9f680cf35a/mmengine/registry/build_functions.py#L117

but it will not influence the interface of `build_from_cfg` at least.

Back to the point, is it necessary to build the visualizer with the same name repeatedly? If the requirement is reasonable, a workaround could be that we could provide a special build function for all `ManagerMixin` classes to resolve this problem.

**Comment by sanbuphy** [comment]
> ild a globally accessible instance with the same name repeatedly:



> > > Thanks for your feedback. Do you mean that [`get_instance`](https://github.com/open-mmlab/mmengine/blob/ce7d742407b8ece2afdff7dc09c9ad9f680cf35a/mmengine/utils/manager.py#L80) will throw an error if the instance with the same `name` has been created? I may not fully understand the case you described, could you please give a simple example to help me understand it?
> > 
> > 
> > For example,we try to build a visualizer:
> > > from mmdet.registry import VISUALIZERS
> > > visualizer = VISUALIZERS.build(model.cfg.visualizer)
> > > visualizer.dataset_meta = model.dataset_meta
> > 
> > 
> > now we have the instance of `model.cfg.visualizer`,If we use `visualizer = VISUALIZERS.build(model.cfg.visualizer)` again, we will meet wrong:
> > ```
> > class `DetLocalVisualizer` in mmdet/visualization/local_visualizer.py: <class 'mmdet.visualization.local_visualizer.DetLocalVisualizer'> instance named of visualizer has been created, the method `get_instance` should not access any other arguments.
> > In this case,we should use `visualizer_now = Visualizer.get_current_instance()` to get the instance.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But i think if we add some option in build（build from cfg) like: `visualizer = VISUALIZERS.build(model.cfg.visualizer, get_instance = True)` Although the visualizer repeatedly created,we will get the instance instead of throwing an exception.We don't need to use `get_current_instance`.
> > If we choose False: `visualizer = VISUALIZERS.build(model.cfg.visualizer, get_instance = False)` it will throw the `DetLocalVisualizer` exception.
> 
> Got it. I think the core issue is that should we build a globally accessible instance with the same name repeatedly:
> 
> * Visualizer inherits from `ManagerMixin`, and can be accessed anywhere by calling `get_instance` or `get_current_instance` method. Since global instance is very dangerous in programming, each `Visualizer` instance has a unique name, and we should not build a visualizer instance with the same name. This is why we could not call `Visualizer.get_instance` with constructing arguments repeatedly(If you call `get_instance` only with the argument `name`, it can return a pre-built `Visualizer` instance).
> * `build_from_cfg` is a build function for general classes, it should not involve too much class-relevant logic. Although there is still some code coupled with `ManagerMixin` like
>   https://github.com/open-mmlab/mmengine/blob/ce7d742407b8ece2afdff7dc09c9ad9f680cf35a/mmengine/registry/build_functions.py#L117
> 
> but it will not influence the interface of `build_from_cfg` at least.
> 
> Back to the point, is it necessary to build the visualizer with the same name repeatedly? If the requirement is reasonable, a workaround could be that we could provide a special build function for all `ManagerMixin` classes to resolve this problem.

Thank you for your detailed answer. In fact, I meet the problem when i use 
```python
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmengine.runner import Runner

# build the runner from config
runner = Runner.from_cfg(cfg)
```
It have built a visualizer.
```python
visualizer = dict(
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        dict(type='TensorboardVisBackend')
    ],
    name='visualizer')
```
but i want to use visualizer to show the result. I don't know how to get the instance `visualizer` and meet the problem when I use `new_visualizer = VISUALIZERS.build(model.cfg.visualizer)`.
Finally i find the `get_current_instance` in mmengine documentation.

But i don't know why we need to build the visualizer in this case:
```python 

from mmdet.apis import init_detector, inference_detector
from mmdet.utils import register_all_modules
from mmdet.registry import VISUALIZERS
import mmcv
register_all_modules()
config_file = './checkpoints/yolov3_mobilenetv2_8xb24-320-300e_coco.py'
checkpoint_file = './checkpoints/yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')  # or device='cuda:0'
image = mmcv.imread( "demo/demo.jpg", channel_order='rgb')
result = inference_detector(model, image)

visualizer = VISUALIZERS.build(model.cfg.visualizer)
visualizer.dataset_meta = model.dataset_meta
visualizer.add_datasample(
    'result',
    image,
    data_sample=result,
    draw_gt = None,
    show=None,
    wait_time=0,
)
```

**Comment by HAOCHENYE** [comment]
Do you mean `visualizer = VISUALIZERS.build(model.cfg.visualizer)` will raise an error?

**Comment by sanbuphy** [comment]
> Do you mean `visualizer = VISUALIZERS.build(model.cfg.visualizer)` will raise an error?
Yes, If we use `runner = Runner.from_cfg(cfg)` before, it seems like every modules have built.
If i use `visualizer = VISUALIZERS.build(model.cfg.visualizer)`, it will raise:
`class `DetLocalVisualizer` in mmdet/visualization/local_visualizer.py: <class 'mmdet.visualization.local_visualizer.DetLocalVisualizer'> instance named of visualizer has been created, the method `get_instance` should not access any other arguments.
In this case,we should use `visualizer_now = Visualizer.get_current_instance()` to get the instance.`

**Comment by HAOCHENYE** [comment]
Practically, we suggest showing the image from the pre-built visualizer. If you really need to build a new visualizer with custom arguments, you can provide a new instance name and build the visualizer with `Visualizer.get_instance()`.

**Comment by sanbuphy** [comment]
> Practically, we suggest showing the image from the pre-built visualizer. If you really need to build a new visualizer with custom arguments, you can provide a new instance name and build the visualizer with `Visualizer.get_instance()`.

OK, I get it.  I have another question.
If we use `register_all_modules()` and ` init_detector`,the visualizer will not be created unless we use VISUALIZERS.build(model.cfg.visualizer). It is right?

**Comment by HAOCHENYE** [comment]
Actually, `VISUALIZERS.build`, `build_from_cfg(VISUALIZERS, cfg)` and `get_instance` is equivalent to each other, the only difference is that the former two building types could build a visualizer from a `cfg`, the latter one we should pass the arguments explicitly.

**Comment by sanbuphy** [comment]
> Actually, `VISUALIZERS.build`, `build_from_cfg(VISUALIZERS, cfg)` and `get_instance` is equivalent to each other, the only difference is that the former two building types could build a visualizer from a `cfg`, the latter one we should pass the arguments explicitly.

OK, I get it.
for `get_instance`, actually I want to say `get_current_instance()`  not `get_instance`

**Comment by zhaohai1314** [comment]
so,how do you solve this problem? i met the same ,,,i am  waiting the solution
