### ISSUE TITLE
Calling for community help on documentation translation

### ISSUE THREAD

**Issue by C1rN09** [open-mmlab/mmengine#677]
Dear community,

We are excited to announce that our **new Chinese documentations are coming soon!** In this version we put some efforts to make it more smooth for newcomers. Hope you'll like it! However, if you find any part of the docs hard to understand, you are free to **give us feedback/suggestions** through [our discussion board](https://github.com/open-mmlab/mmengine/discussions)!

With the near release of Chinese docs, English translations are scheduled. We select some Chinese docs and call for community help on **translations into English**. Below is a table of all available docs, together with their scheduled due and assigned volunteers(currently empty, of course). If you are interested in either of them, you can **claim it by replying this issue!**

| Docs to translate | Registration due | Finish due | Assigned to |
| ----------------- | ---------------- | ----------- | ----------- |
| examples/resume_training | 11.10 | 11.15 | |
| examples/speed_up_training | 11.10 | 11.15 | |
| examples/save_gpu_memory | 11.10 | 11.15 | |
| examples/train_a_gan | 11.10 | 11.15 | |
| migration/runner | 11.10 | 11.15 | |
| migration/hook | 11.10 | 11.15 | |
| migration/model | 11.10 | 11.15 | |
| migration/param_scheduler | 11.10 | 11.15 | |
| migration/transform | 11.10 | 11.15 | |

Some extra notes:

1. We welcome new contributors to participate in this event! Don't worry if you haven't posted a PR so far. We'll provide detailed guides on how to post a PR in MMEngine after registration due.
2. If you are interested in this, you can reply this issue **before registration due**. Once assigned, you are encouraged to finish translation and post a PR **before finish due**.
3. All modifications & PRs should be based on `docs_refactor` branch. Don't be confused!

We may invite @HAOCHENYE @zhouzaida @ice-tong to see if there's any misspelling in this issue.

**Comment by HAOCHENYE** [comment]
![image](https://user-images.githubusercontent.com/57566630/199933679-abc577db-dc2f-46d8-99bb-f8d5e14a5303.png)
