### ISSUE TITLE
Add video to tensorboard using Visualizer

### ISSUE THREAD

**Issue by PingHGao** [open-mmlab/mmengine#678]
In the Visualizer module，we can add single image to the Visualizer and then save it to tensorboard. But I do not see how to add video to the Visualizer which we can use `add_video()` in tensorboard writers. So I request to add this feature.

**Comment by HAOCHENYE** [comment]
Thanks for your suggestions! we may invite @hhaAndroid and @Harold-lkk to have a lool.
