### ISSUE TITLE
Log issues when using two GPUs

### ISSUE THREAD

**Issue by PingHGao** [open-mmlab/mmengine#688]
I have a training dataset which have 3425 items. When training with `batch_size = 4`, the log is:

```
2022/11/07 10:41:22 - mmengine - INFO - Epoch(train) [1][10/857]  lr: 1.0000e-04 
```
which means the length of the data_loader  857. This is correct. 
**But when I use 2 GPUs, the log remains the same!** It also says the data_loader's length is 857, which should be half because the batch_size is doubled with two GPUs. I can see that each GPU is processing 4 batch data through the GPU memory comsumption. 
Is there anything wrong with data_loader or logger? Please help!

**Comment by PingHGao** [comment]
I have just tried the official example `examples/train.py`, which is the same.
Does the `examples/train.py` is just an example to show how to use two gpus and it do not provide the correct way to create a dataloader?

**Comment by HAOCHENYE** [comment]
Thanks for your feedback! It seems that `examples/train.py` does not configure a distributed sampler for Dataloadera correctly, which contributes to the error indices in Dataloader. Would you mind trying  to configure the Dataloader with the [DefaultSampler](https://github.com/open-mmlab/mmengine/blob/ed20a9cba52ceb371f7c825131636b9e2747172e/mmengine/dataset/sampler.py#L14)  in `examples/train.py`? If it works, it could be helpful to post a PR to fix the example :smile:

**Comment by PingHGao** [comment]
> Thanks for your feedback! It seems that `examples/train.py` does not configure a distributed sampler for Dataloadera correctly, which contributes to the error indices in Dataloader. Would you mind trying to configure the Dataloader with the [DefaultSampler](https://github.com/open-mmlab/mmengine/blob/ed20a9cba52ceb371f7c825131636b9e2747172e/mmengine/dataset/sampler.py#L14) in `examples/train.py`? If it works, it could be helpful to post a PR to fix the example smile

After configure the dataloader with `DefaultSampler`, the problem remains. The dataloader is as below. I find that the 2 GPU is running with the command `python -m torch.distributed.launch --nproc_per_node=2 examples/train.py --launcher pytorch`, but the code `print(get_dist_info())` gives `0, 1` in each process.
```
train_set = torchvision.datasets.CIFAR10(
            'data/cifar10',
            train=True,
            download=True,
            transform=transforms.Compose([
                transforms.RandomCrop(32, padding=4),
                transforms.RandomHorizontalFlip(),
                transforms.ToTensor(),
                transforms.Normalize(**norm_cfg)
            ]))
    valid_set = torchvision.datasets.CIFAR10(
            'data/cifar10',
            train=False,
            download=True,
            transform=transforms.Compose(
                [transforms.ToTensor(),
                 transforms.Normalize(**norm_cfg)]))
    train_dataloader = DataLoader(
        batch_size=32,
        shuffle=False,
        dataset=train_set,
        sampler=DefaultSampler(train_set, shuffle=True)
    )
    val_dataloader = DataLoader(
        batch_size=32,
        shuffle=False,
        dataset=valid_set,
        sampler=DefaultSampler(valid_set, shuffle=True)
    )
```

**Comment by PingHGao** [comment]
I finished one version of the example code. But I do not know whether it will work correctly or not. Please give an wonderful official example. The code I figure out is as below:
```python
# Copyright (c) OpenMMLab. All rights reserved.
import argparse
import os

import torch
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.optim import SGD
from torch.utils.data import DataLoader
import torch.distributed as dist

from mmengine.evaluator import BaseMetric
from mmengine.model import BaseModel
from mmengine.runner import Runner
from mmengine.dataset import DefaultSampler
from mmengine.dist import get_dist_info, sync_random_seed

class MMResNet50(BaseModel):

    def __init__(self):
        super().__init__()
        self.resnet = torchvision.models.resnet50()

    def forward(self, imgs, labels, mode):
        x = self.resnet(imgs)
        if mode == 'loss':
            return {'loss': F.cross_entropy(x, labels)}
        elif mode == 'predict':
            return x, labels


class Accuracy(BaseMetric):

    def process(self, data_batch, data_samples):
        score, gt = data_samples
        self.results.append({
            'batch_size': len(gt),
            'correct': (score.argmax(dim=1) == gt).sum().cpu(),
        })

    def compute_metrics(self, results):
        total_correct = sum(item['correct'] for item in results)
        total_size = sum(item['batch_size'] for item in results)
        return dict(accuracy=100 * total_correct / total_size)


def parse_args():
    parser = argparse.ArgumentParser(description='Distributed Training')
    parser.add_argument(
        '--launcher',
        choices=['none', 'pytorch', 'slurm', 'mpi'],
        default='none',
        help='job launcher')
    parser.add_argument('--local_rank', type=int, default=0)

    args = parser.parse_args()
    return args


def main():
    args = parse_args()

    if args.launcher != "none":
        rank = int(os.environ['RANK'])
        num_gpus = torch.cuda.device_count()
        torch.cuda.set_device(rank % num_gpus)
        dist.init_process_group(backend="nccl", world_size=2, rank=rank)

    norm_cfg = dict(mean=[0.491, 0.482, 0.447], std=[0.202, 0.199, 0.201])
    train_set = torchvision.datasets.CIFAR10(
            'data/cifar10',
            train=True,
            download=True,
            transform=transforms.Compose([
                transforms.RandomCrop(32, padding=4),
                transforms.RandomHorizontalFlip(),
                transforms.ToTensor(),
                transforms.Normalize(**norm_cfg)
            ]))
    valid_set = torchvision.datasets.CIFAR10(
            'data/cifar10',
            train=False,
            download=True,
            transform=transforms.Compose(
                [transforms.ToTensor(),
                 transforms.Normalize(**norm_cfg)]))
    train_dataloader = DataLoader(
        batch_size=32,
        shuffle=False,
        dataset=train_set,
        sampler=DefaultSampler(train_set, shuffle=True)
    )
    val_dataloader = DataLoader(
        batch_size=32,
        shuffle=False,
        dataset=valid_set,
        sampler=DefaultSampler(valid_set, shuffle=True)
    )

    runner = Runner(
        model=MMResNet50(),
        work_dir='./work_dir',
        train_dataloader=train_dataloader,
        optim_wrapper=dict(optimizer=dict(type=SGD, lr=0.001, momentum=0.9)),
        train_cfg=dict(by_epoch=True, max_epochs=2, val_interval=1),
        val_dataloader=val_dataloader,
        val_cfg=dict(),
        val_evaluator=dict(type=Accuracy),
        launcher=args.launcher,
    )
    runner.train()


if __name__ == '__main__':
    main()
```

**Comment by HAOCHENYE** [comment]
> I finished one version of the example code. But I do not know whether it will work correctly or not. Please give an wonderful official example. The code I figure out is as below:
> 
> ```python
> # Copyright (c) OpenMMLab. All rights reserved.
> import argparse
> import os
> 
> import torch
> import torch.nn.functional as F
> import torchvision
> import torchvision.transforms as transforms
> from torch.optim import SGD
> from torch.utils.data import DataLoader
> import torch.distributed as dist
> 
> from mmengine.evaluator import BaseMetric
> from mmengine.model import BaseModel
> from mmengine.runner import Runner
> from mmengine.dataset import DefaultSampler
> from mmengine.dist import get_dist_info, sync_random_seed
> 
> class MMResNet50(BaseModel):
> 
>     def __init__(self):
>         super().__init__()
>         self.resnet = torchvision.models.resnet50()
> 
>     def forward(self, imgs, labels, mode):
>         x = self.resnet(imgs)
>         if mode == 'loss':
>             return {'loss': F.cross_entropy(x, labels)}
>         elif mode == 'predict':
>             return x, labels
> 
> 
> class Accuracy(BaseMetric):
> 
>     def process(self, data_batch, data_samples):
>         score, gt = data_samples
>         self.results.append({
>             'batch_size': len(gt),
>             'correct': (score.argmax(dim=1) == gt).sum().cpu(),
>         })
> 
>     def compute_metrics(self, results):
>         total_correct = sum(item['correct'] for item in results)
>         total_size = sum(item['batch_size'] for item in results)
>         return dict(accuracy=100 * total_correct / total_size)
> 
> 
> def parse_args():
>     parser = argparse.ArgumentParser(description='Distributed Training')
>     parser.add_argument(
>         '--launcher',
>         choices=['none', 'pytorch', 'slurm', 'mpi'],
>         default='none',
>         help='job launcher')
>     parser.add_argument('--local_rank', type=int, default=0)
> 
>     args = parser.parse_args()
>     return args
> 
> 
> def main():
>     args = parse_args()
> 
>     if args.launcher != "none":
>         rank = int(os.environ['RANK'])
>         num_gpus = torch.cuda.device_count()
>         torch.cuda.set_device(rank % num_gpus)
>         dist.init_process_group(backend="nccl", world_size=2, rank=rank)
> 
>     norm_cfg = dict(mean=[0.491, 0.482, 0.447], std=[0.202, 0.199, 0.201])
>     train_set = torchvision.datasets.CIFAR10(
>             'data/cifar10',
>             train=True,
>             download=True,
>             transform=transforms.Compose([
>                 transforms.RandomCrop(32, padding=4),
>                 transforms.RandomHorizontalFlip(),
>                 transforms.ToTensor(),
>                 transforms.Normalize(**norm_cfg)
>             ]))
>     valid_set = torchvision.datasets.CIFAR10(
>             'data/cifar10',
>             train=False,
>             download=True,
>             transform=transforms.Compose(
>                 [transforms.ToTensor(),
>                  transforms.Normalize(**norm_cfg)]))
>     train_dataloader = DataLoader(
>         batch_size=32,
>         shuffle=False,
>         dataset=train_set,
>         sampler=DefaultSampler(train_set, shuffle=True)
>     )
>     val_dataloader = DataLoader(
>         batch_size=32,
>         shuffle=False,
>         dataset=valid_set,
>         sampler=DefaultSampler(valid_set, shuffle=True)
>     )
> 
>     runner = Runner(
>         model=MMResNet50(),
>         work_dir='./work_dir',
>         train_dataloader=train_dataloader,
>         optim_wrapper=dict(optimizer=dict(type=SGD, lr=0.001, momentum=0.9)),
>         train_cfg=dict(by_epoch=True, max_epochs=2, val_interval=1),
>         val_dataloader=val_dataloader,
>         val_cfg=dict(),
>         val_evaluator=dict(type=Accuracy),
>         launcher=args.launcher,
>     )
>     runner.train()
> 
> 
> if __name__ == '__main__':
>     main()
> ```

So sorry for the unpleasant experience 😭 , we'll fix it ASAP and @ you in this issue.

**Comment by C1rN09** [comment]
Hi, @PingHGao ! You can use MMEngine's util function to initialize distributed environment, as below

```python
from mmengine.dist import init_dist

def main():
    args = parse_args()

    ## Change these lines to `init_dist` below
    # if args.launcher != "none":
    #     rank = int(os.environ['RANK'])
    #     num_gpus = torch.cuda.device_count()
    #     torch.cuda.set_device(rank % num_gpus)
    #     dist.init_process_group(backend="nccl", world_size=4, rank=rank)
    init_dist(args.launcher)
```

The reason why your original code (and our example code, of course) works incorrectly is that the `DefaultSampler` is initialized **before** distributed environment setup. Adding `init_dist` to the very beginning solves it.

However if you want to make your code more clean and don't want to write `init_dist` at the beginning, you can try writing your pipeline with `dict` parameters as below

```python
def main():
    args = parse_args()

    ## These lines are not needed
    # if args.launcher != "none":
    #     rank = int(os.environ['RANK'])
    #     num_gpus = torch.cuda.device_count()
    #     torch.cuda.set_device(rank % num_gpus)
    #     dist.init_process_group(backend="nccl", world_size=2, rank=rank)

    train_set = torchvision.datasets.CIFAR10(...)  # Same as your code
    train_dataloader = dict(  # Note we use `dict` here
        batch_size=32,
        dataset=train_set,
        sampler=dict(type='DefaultSampler', shuffle=True)  # Another `dict` here
    )
    runner = Runner(
        ...  # Same as your code
    )
```

Parameters given as `dict` will be lazily built in `Runner` and we make sure it is in correct order.

We apologize for our wrong example & tutorial which made you confused. We are currently working on better documentations and your feedback is valuable!

Finally, since you have written your version of example code, could you **post a PR to solve the wrong example**? Thank you!

**Comment by PingHGao** [comment]
Thanks for your timely help! I have post a PR to solve this. #700
