### ISSUE TITLE
Import ProcessGroup fail

### ISSUE THREAD

**Issue by ayicherry** [open-mmlab/mmengine#699]
windows系统下，在使用mmocr 1.x的时候，出现cannot import name 'ProcessGroup' from 'torch.distributed'的错误，该代码是在mmengine中，目前mmengine的版本是0.2.0，torch的版本是1.6.0。不知道有哪位大佬遇到过这个问题的？

**Comment by zhouzaida** [comment]
你好，该问题可以通过升级 torch 的版本至 1.7 或者更高解决。我们也会尝试去解决该问题。

**Comment by zhouzaida** [comment]
你好，这个是 pytorch1.6 版本的问题，建议升级至 pytorch1.7 或者更高的版本
