### ISSUE TITLE
[Feature] MMEngine English documentation

### ISSUE THREAD

**Issue by main-2983** [open-mmlab/mmengine#721]
### What is the feature?

Please update MMEngine documentation in English as well  
Since every OpenMMLab projects like MMSegmentation, MMDetection,... are moving into using MMEngine and not being able to understand MMEngine is really hard to use others

**Comment by C1rN09** [comment]
English documentation translation is in progress and will be completed by approximately next week. You may find some docs already translated in "docs_refactor" branch.

**Comment by zhouzaida** [comment]
solved by https://github.com/open-mmlab/mmengine/pull/786
