### ISSUE TITLE
Problem of `SegLocalVisualizer._draw_sem_seg` in mmsegmentation 1.x. 

### ISSUE THREAD

**Issue by Li-Qingyun** [open-mmlab/mmengine#741]
I tried to visualize semantic segmentation map of Potsdam data set with `browse_dataset.py`, which uses `SegLocalVisualizer._draw_sem_seg` to draw the map. The results are as follows:

![2_10_0_0_512_512 png_0](https://user-images.githubusercontent.com/79644233/202074344-b6c17b35-73b9-4a36-8845-1ac54f4edef6.png)
![image](https://user-images.githubusercontent.com/79644233/202095758-f5419b3f-a8b5-4851-9a2e-4dd0b714fb40.png)

I wrote a custom visualizer according to the mmseg0.x to replace the original `_draw_sem_seg`, and show the fis:

![image](https://user-images.githubusercontent.com/79644233/202096207-64b21318-bbbe-4a90-9055-8fc348552e6d.png)
![image](https://user-images.githubusercontent.com/79644233/202096258-a074e39c-c078-4941-a0e2-b0beea8706a1.png)

I asked the question in WeChat community, the other users also meet the problam in demo:

![mmexport1668578455894](https://user-images.githubusercontent.com/79644233/202097001-77dbb706-211a-4bbe-a2c3-c2b28b896cca.png)

### Script
My custom visualizer is:
```Python
from typing import Optional, Tuple, List

import numpy as np
from mmengine.structures import PixelData
from mmseg.registry import VISUALIZERS
from mmseg.visualization import SegLocalVisualizer


@VISUALIZERS.register_module()
class MyVisualizer(SegLocalVisualizer):

    def _draw_sem_seg(self, image: np.ndarray, sem_seg: PixelData,
                      classes: Optional[Tuple[str]],
                      palette: Optional[List[List[int]]]) -> np.ndarray:
        """Draw semantic seg of GT or prediction.

        Args:
            image (np.ndarray): The image to draw.
            sem_seg (:obj:`PixelData`): Data structure for
                pixel-level annotations or predictions.
            classes (Tuple[str], optional): Category information.
            palette (List[List[int]], optional): The palette of
                segmentation map.

        Returns:
            np.ndarray: the drawn image which channel is RGB.
        """
        sem_seg = sem_seg.cpu().data[0]

        color_seg = np.zeros((sem_seg.shape[0], sem_seg.shape[1], 3), dtype=np.uint8)
        for label, color in enumerate(palette):
            color_seg[sem_seg == label, :] = color

        image = image * (1 - self.alpha) + color_seg * self.alpha
        image = image.astype(np.uint8)

        return image

```

**Comment by Li-Qingyun** [comment]
> May you check the color of the shadow area in this picture? and figure out which label index responds to the color? https://user-images.githubusercontent.com/79644233/202074344-b6c17b35-73b9-4a36-8845-1ac54f4edef6.png

```
>>> np.unique(xx)
array([0.        , 0.0627451 , 0.10196079, 0.10588235, 0.10980392,
       0.11372549, 0.11764706, 0.12941177, 0.13333334, 0.13725491,
       0.14117648, 0.14509805, 0.14901961, 0.15294118, 0.15686275,
       0.16078432, 0.16470589, 0.16862746, 0.17254902, 0.1764706 ,
       0.18039216, 0.18431373, 0.1882353 , 0.19215687, 0.19607843,
       0.2       , 0.20392157, 0.20784314, 0.21176471, 0.21568628,
       0.21960784, 0.22352941, 0.22745098, 0.23137255, 0.23529412,
       0.23921569, 0.24313726, 0.24705882, 0.2509804 , 0.25490198,
       0.25882354, 0.2627451 , 0.26666668, 0.27058825, 0.27450982,
       0.2784314 , 0.28235295, 0.28627452, 0.2901961 , 0.29411766,
       0.29803923, 0.3019608 , 0.30588236, 0.30980393, 0.3137255 ,
       0.31764707, 0.32156864, 0.3254902 , 0.32941177, 0.33333334,
       0.3372549 , 0.34117648, 0.34509805, 0.34901962, 0.3529412 ,
       0.35686275, 0.36078432, 0.3647059 , 0.36862746, 0.37254903,
       0.3764706 , 0.38039216, 0.38431373, 0.3882353 , 0.39215687,
       0.39607844, 0.4       , 0.40392157, 0.40784314, 0.4117647 ,
       0.41568628, 0.41960785, 0.42352942, 0.42745098, 0.43137255,
       0.43529412, 0.4392157 , 0.44313726, 0.44705883, 0.4509804 ,
       0.45490196, 0.45882353, 0.4627451 , 0.46666667, 0.47058824,
       0.4745098 , 0.47843137, 0.48235294, 0.4862745 , 0.49019608,
       0.49411765, 0.49803922, 0.5019608 , 0.5058824 , 0.50980395,
       0.5137255 , 0.5176471 , 0.52156866, 0.5254902 , 0.5294118 ,
       0.53333336, 0.5372549 , 0.5411765 , 0.54509807, 0.54901963,
       0.5529412 , 0.5568628 , 0.56078434, 0.5647059 , 0.5686275 ,
       0.57254905, 0.5764706 , 0.5803922 , 0.58431375, 0.5882353 ,
       0.5921569 , 0.59607846, 0.6       , 0.6039216 , 0.60784316,
       0.6117647 , 0.61960787, 0.62352943, 0.627451  , 0.6313726 ,
       0.63529414, 0.6392157 , 0.6431373 , 1.        ], dtype=float32)
```

![image](https://user-images.githubusercontent.com/79644233/202650919-a4443926-7170-4681-903e-fcda2902cef6.png)

**Comment by Li-Qingyun** [comment]
I also tried ADE20K:

in a new env:
```shell
conda create -n mmseg-show-test python=3.8
pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html
pip install openmim
mim install mmengine 'mmcv>=2.0.0rc0' 'mmsegmentation>=1.0.0rc0'
```

running command is:

```shell
mim run mmseg browse_dataset configs/fcn/fcn_r50-d8_4xb4-160k_ade20k-512x512.py --output-dir browser_datasets/ade20k --not-show
```

The results are:

![ADE_train_00000001 jpg_0](https://user-images.githubusercontent.com/79644233/202651685-7b5d1099-9380-4f06-b461-ae756220d42a.png)


![ADE_train_00000002 jpg_0](https://user-images.githubusercontent.com/79644233/202651700-3eaee952-a170-4b23-a8ae-d6d30d2322ca.png)


![ADE_train_00000003 jpg_0](https://user-images.githubusercontent.com/79644233/202651711-9366886d-3bee-48e4-9b60-494d078f5b7f.png)

```Python
mim run mmseg browse_dataset configs/fcn/fcn_r50-d8_4xb4-160k_ade20k-512x512.py --output-dir browser_datasets/ade20k --not-show --cfg-option visualizer.alpha=1
```

![ADE_train_00000001 jpg_0](https://user-images.githubusercontent.com/79644233/202652414-003c12f0-6c11-4a69-9862-266d210b3131.png)

![ADE_train_00000002 jpg_0](https://user-images.githubusercontent.com/79644233/202652437-820fab6f-7ff8-4c34-a16c-90728f329909.png)

![ADE_train_00000003 jpg_0](https://user-images.githubusercontent.com/79644233/202652457-425dfeae-8890-40dc-8b0d-65e376f7340b.png)

![ADE_train_00000004 jpg_0](https://user-images.githubusercontent.com/79644233/202652476-fa5a4e76-fe44-4eda-84b2-0048d9ee76c7.png)

**Comment by Li-Qingyun** [comment]
> @Li-Qingyun Thanks for your report! In MMEngine, In `draw_binary_masks`, only the mask region in the image will add the weighted color, and the unmask region in the image will keep its original pixels.

Thanks for your reply, but, in this figure, it seems that there is not `unmask regions` in the semantic map. Because each pixel belongs to one category of 0, 1, 2, 3, 4, 5.
![image](https://user-images.githubusercontent.com/79644233/205468286-a1b01fdf-3234-4d94-89ac-37857c0b5e8b.png)

Whether the visualization of semantic segmentation results and dataset browsing should use this feature-rich `draw_binary_masks`.

I still do not understand why there is confusing boundary in my segmentation map.

**Comment by collinmccarthy** [comment]
For what it's worth I'm having the same issue here
