### ISSUE TITLE
Neptune collaboration 🚀 ! 

### ISSUE THREAD

**Issue by HAOCHENYE** [open-mmlab/mmengine#765]
@kshitij12345 @Blaizzy @fcakyon  Hi! Let's discuss the roadmap or something else here 😆 ! Also invite @ZwwWayne

**Comment by Blaizzy** [comment]
Hey @HAOCHENYE!

Do you mind sharing when will MMDetection 3.x be released? And what are the main breaking changes from MMDetection 2.x?

cc: @kshitij12345

**Comment by HAOCHENYE** [comment]
We've pre-release the MMDet in the 3.x branch, and will release it in the January of next year. We can see the main difference in the changelog 
![image](https://user-images.githubusercontent.com/57566630/204079496-b7200c4e-14eb-42a8-abfb-2a4f40dd2b0e.png)

If we want to discuss it more detailed, how about communicating in Slack or discord?

**Comment by kshitij12345** [comment]
I think Slack or discord would be really helpful. I tried searching for getting invite to Slack or Discord of `open-mmlab` but couldn't find one. How can we register for either of them (and which channel would you prefer?) 

Thank you!

**Comment by HAOCHENYE** [comment]
> I think Slack or discord would be really helpful. I tried searching for getting invite to Slack or Discord of `open-mmlab` but couldn't find one. How can we register for either of them (and which channel would you prefer?)
> 
> Thank you!

So sorry for my late reply, we spend some time discussing whether to choose slack or Discord as our communication tool :rofl: , And finally we choose Discord. I'm a newbie to Discord, and I try to make an invitation like this: 

https://discord.gg/aRjUQJRd

I'm not sure will it work :rofl:

**Comment by fcakyon** [comment]
@kshitij12345 is there any progress or ETA on adding Neptune support to mmengine? :)

**Comment by kshitij12345** [comment]
@kshitij12345 Thanks for reaching out. As of now, there isn't much progress. Give me a couple of days to get a clear ETA on the same. Thank you very much :)

**Comment by fcakyon** [comment]
Thanks a lot @kshitij12345. We might be interested in actively using mmdetection 3.x, and mmyolo but the lack of Neptune support is a big issue for us 😅

**Comment by kshitij12345** [comment]
@fcakyon Thank you for letting us know! I have taken a note of this and will get back to you in a couple of days :)

**Comment by kshitij12345** [comment]
@fcakyon I am sorry but will need a bit more time to get back with the holiday season :)

Happy Holidays :)

**Comment by fcakyon** [comment]
> @fcakyon I am sorry but will need a bit more time to get back with the holiday season :)
> 
> Happy Holidays :)

Have a great holiday :)

**Comment by Blaizzy** [comment]
Hey guys 

I want to introduce you to @AleksanderWWW, the ML integration engineer at Neptune in charge of the implementation.

We are still working with v2 but later would like to build for v3.

**Comment by AleksanderWWW** [comment]
Hi everyone! 😃

**Comment by HAOCHENYE** [comment]
> Hi everyone! smiley

Hi, would you mind joining the discord group for the further communication :smile: ?

https://discord.gg/jkP6Ru6UTj

**Comment by zhouzaida** [comment]
closed by #1311
