### ISSUE TITLE
[Enhance] EpochBasedTrainLoop supports epochs with floating-point numbers

### ISSUE THREAD

**Issue by wangjiangben-hw** [open-mmlab/mmengine#785]
### What is the feature?

At present, EpochBasedTrainLoop only supports integers, and in some performance test scenarios, there may be scenarios such as 0.1 that want to run part of epoch, hoping to support such scenarios

### Any other context?
An implementation example is provided for informational purposes only..
![image](https://user-images.githubusercontent.com/111729245/205270055-f5e357e8-a5ef-43a1-b179-8469c06b19bf.png)

**Comment by HAOCHENYE** [comment]
Thank your for your suggestion. If you want to only train several iterations,  you can configure `indices` in [`BaseDataset`](https://github.com/open-mmlab/mmengine/blob/7e787d8ffa32c2bd26e8b826376020d287d6e3d5/mmengine/dataset/base_dataset.py#L219). Then runner only will train with the subset of the original dataset.

**Comment by wangjiangben-hw** [comment]
OK, that's a different way of thinking. 
In fact, I think that if you can set 0.1 epoch, it should be more direct than setting the length in the dataset
