### ISSUE TITLE
[Feature] pytorch-2.0

### ISSUE THREAD

**Issue by MiXaiLL76** [open-mmlab/mmengine#842]
### What is the feature?

https://pytorch.org/get-started/pytorch-2.0/?utm_source=linkedin&utm_medium=organic_social&utm_campaign=pytorch_conference

Any ideas on how to apply new versions of the framework?

**Comment by C1rN09** [comment]
You may want to try our [experimental/compile](https://github.com/open-mmlab/mmengine/tree/experimental/compile) branch.

As PyTorch official statement, `torch.compile` is optional and the API might be change, so we only created an **experimental branch** for users to have a try. This feature should be brought to `main` branch after official release of PyTorch 2.0.

Currently, models may fail compilation. We are testing our models and will post issues to PyTorch. Hopefully, you will see all OpenMMLab models accelerated by `torch.compile` after its official release 😄
