### ISSUE TITLE
[Bug]  mmengine - ERROR - /usr/local/miniconda3/lib/python3.8/site-packages/mmdet/evaluation/metrics/coco_metric.py - compute_metrics - 437 - The testing results of the whole dataset is empty.

### ISSUE THREAD

**Issue by Jerryyyy0** [open-mmlab/mmengine#845]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

<img width="393" alt="image" src="https://user-images.githubusercontent.com/88527556/209457522-1a2d7198-39df-40c6-af8a-5b9d51f7d80d.png">

### Reproduces the problem - code sample

mmyolo训练时出现错误

### Reproduces the problem - command or script

mmyolo tools/train.py

### Reproduces the problem - error message

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/88527556/209457479-97106f41-8160-4f44-811b-c773e9f55e74.png">

**Comment by zhouzaida** [comment]
Hi @Jerryyyy0 , thanks for your feedback. Are you interested in making a PR to fix this issue?

Adding a condition to check whether metrics are empty.

https://github.com/open-mmlab/mmengine/blob/e83ac944b6e380781ea42a714a55a33c075cc904/mmengine/hooks/checkpoint_hook.py#L297

**Comment by Jerryyyy0** [comment]
ok, I will try again.
