### ISSUE TITLE
[Feature] Get rid of "Exp Name" after every training epoch

### ISSUE THREAD

**Issue by JunweiZheng93** [open-mmlab/mmengine#866]
### What is the feature?

MMEngine is an amazing package and thx for your effort. Since I am a huge fan of `EpochBasedTrainLoop`, I prefer logging my results once an epoch and therefore, I will only have a few lines for logging. The experiment name still shows up every epoch even though I set `interval_exp_name ` to zero, which drives me crazy. May I kindly ask for deleting the experiment name after every training epoch? Modifying [this line](https://github.com/open-mmlab/mmengine/blob/f10b5cefd97ccc03bb78bc40b39fb41428b46ef9/mmengine/hooks/logger_hook.py#L155) might be enough.

For those who prefer `IterBasedTrainLoop` and have lots of lines to log, I think they will set a proper value for `interval_exp_name `. It is not necessary to still log the experiment name after every training epoch.

Have a nice day.

**Comment by HAOCHENYE** [comment]
Thanks for your feedback, logging `exp_name` each epoch will be useful for those small dataset. It means that whether it is a large or small dataset, users can always output exp_name during training.

We are planning to develop a new feature that will allow users to block logs of specified modules or regular expressions, which may help you. Stay tuned :laughing: !

**Comment by JunweiZheng93** [comment]
Hi, thx and looking forward to that. Close.
