### ISSUE TITLE
[Docs] ModuleNotFoundError: No module named 'mmcv.transforms'

### ISSUE THREAD

**Issue by BenoitKAO** [open-mmlab/mmengine#880]
### 📚 The doc issue

https://mmengine.readthedocs.io/zh_CN/latest/examples/train_a_gan.html

构建数据集
...
from mmcv.transforms import to_tensor
...

ModuleNotFoundError: No module named 'mmcv.transforms'
returned

**Comment by zhouzaida** [comment]
Hi @BenoitKAO, you need to install `mmcv>=2.0.0rc1` if you want to use `mmcv.transforms`.

**Comment by BenoitKAO** [comment]
Thank you very much for your prompt answer, and I will try to use mmcv>=2.0.0rc1 later.
