### ISSUE TITLE
[Feature] class visualizer draw_texts() method add a fontproperties argument in order to set Chinese font

### ISSUE THREAD

**Issue by KevinNuNu** [open-mmlab/mmengine#882]
### What is the feature?

https://github.com/open-mmlab/mmengine/blob/9d3f5b21c199a0d249ab148d92fd4d78580e8b6c/mmengine/visualization/visualizer.py#L393-L509
now class visualizer draw_texts() method already has an argument about font —— font_families
but vaule of font_families should be 'serif', 'sans-serif', 'cursive', 'fantasy' or 'monospace', which can not draw Chinese texts proprely.

so i think  add a fontproperties argument is a great method to solve the problem about Chinese texts can not show proprely.

or set a font which can show Chinese texts proprely to font_families?

**Comment by HAOCHENYE** [comment]
Thanks for your feedback :smile: !  The solution of adding the `fontproperties` argument sounds good to me, would you mind posting a PR to help us support showing Chinese characters?

**Comment by KevinNuNu** [comment]
> Thanks for your feedback 😄 ! The solution of adding the `fontproperties` argument sounds good to me, would you mind posting a PR to help us support showing Chinese characters?

I post a [PR](https://github.com/open-mmlab/mmengine/pull/885) about this problem

btw, i want to konw  when we will change the value of font_families and what's the difference between font_families and font_properties?
