### ISSUE TITLE
[Feature] Automatically publish models at the end of training

### ISSUE THREAD

**Issue by RangeKing** [open-mmlab/mmengine#905]
### What is the feature?
Automatically publish the best and the last checkpoints at the end of training.

### Motivation
Users often wonder why the trained model is much larger than the pre-trained model.
The feature requested will solve this problem.

### Related files
https://github.com/open-mmlab/mmengine/blob/main/mmengine/hooks/checkpoint_hook.py
https://github.com/open-mmlab/mmdetection/blob/3.x/tools/model_converters/publish_model.py.

**Comment by zhouzaida** [comment]
It sounds good. How about adding a new parameter `published_keys` which is None by default and implementing a new method `after_hook` to publish the models?

**Comment by RangeKing** [comment]
> It sounds good. How about adding a new parameter `published_keys` which is None by default and implementing a new method `after_hook` to publish the models?

It looks great.

**Comment by KerwinKai** [comment]
> It sounds good. How about adding a new parameter `published_keys` which is None by default and implementing a new method `after_hook` to publish the models?

How about `published_keys (str, List[str], optional)`, which is None by default. And the optional parameters are last and best, both of which can also be selected at the same time (judging whether it is None or Str or List). The optional parameters are `last` and `best`, both of which can also be selected at the same time (judging whether it is `None` or `Str` or `List`). At the same time, the `last` depends on `save_last`, and the `best` depends on `save_best`, that is to say, the parameter `published_keys` can only be executed if one or both of `save_last` and `save_best` are defined. And implementing a new method `after_hook` to publish the models
for example
## not run
> CheckpointHook(interval=2, by_epoch=True, save_last=False, published_keys=['last', 'best'])
## publish last
> CheckpointHook(interval=2, by_epoch=True, published_keys=['last'])
## publish best
> CheckpointHook(interval=2, by_epoch=True, save_last=False, save_best=['FID', 'IS'], rule=['less', 'greater'], published_keys=['best'])
## publish both last and best
>CheckpointHook(interval=2, by_epoch=True, save_best=['FID', 'IS'], rule=['less', 'greater'], published_keys=['last', 'best'])

**Comment by KerwinKai** [comment]
`published_keys (str, List[str], optional)`, which is None by default. When published_keys is not None, implementing a new method `after_hook` to publish the models. This method run behind `save_last` or `save_best`. 


For example: train cifar10(ResNet50):
> train_cfg=dict(by_epoch=True, max_epochs=5, val_interval=1)
>
Here, published_keys defaults to None, so the checkpoint will not be automatically published after the program runs. compare the trained model and the pre-trained model, and then we can see that the trained model is much larger than the pre-trained model. The size of trained model if `205435327` and the size of pre-trained model is '94406447'. This pre-trained model download in mmclassification
```
drwxrwxr-x 3 scz0b6e scz0b6e      4096 Mar  5 16:29 20230305_162941
-rw-rw-r-- 1 scz0b6e scz0b6e         1 Mar  5 16:29 20230305_162941.py
-rw-rw-r-- 1 scz0b6e scz0b6e 204934911 Mar  5 16:30 epoch_1.pth
-rw-rw-r-- 1 scz0b6e scz0b6e 205060479 Mar  5 16:31 epoch_2.pth
-rw-rw-r-- 1 scz0b6e scz0b6e 205185407 Mar  5 16:32 epoch_3.pth
-rw-rw-r-- 1 scz0b6e scz0b6e 205310463 Mar  5 16:33 epoch_4.pth
-rw-rw-r-- 1 scz0b6e scz0b6e 205435327 Mar  5 16:34 epoch_5.pth
-rw-rw-r-- 1 scz0b6e scz0b6e        57 Mar  5 16:34 last_checkpoint
```
```
-rw-rw-r-- 1 scz0b6e scz0b6e 94406447 Mar  5 16:38 resnet50_b16x8_cifar10_20210528-f54bfad9.pth
```
We load the key of the model, we can see that the trained model has four keys, and the pre-trained model has only two keys. This also explains why the size difference between the two checkpoints.

**trained model**
```
['meta', 'state_dict', 'message_hub', 'optimizer']
```

**pre-trained model**
```
['meta', 'state_dict']
```

After introducing the optional parameter `published_keys (str, List[str], optional)`, the implementation uautomatically publish the best and the last checkpoints at the end of training.

> train_cfg=dict(by_epoch=True, max_epochs=5, val_interval=1, published_keys=['meta', 'state_dict'])
>
Here is running log
```
03/05 17:08:28 - mmengine - INFO - Key `message_hub` will be removed because it is not in save_keys. If you want to keep it, please set `message_hub` in published_keys.
03/05 17:08:28 - mmengine - INFO - Key `optimizer` will be removed because it is not in save_keys. If you want to keep it, please set `optimizer` in published_keys.
03/05 17:08:29 - mmengine - INFO - The published model is saved at /HOME/scz0b6e/run/mm-lab/run_place/work_dir/epoch_5-6767878a.pth.
```

After running, we compare the size of the generated checkpoint. The size of `epoch_5-6767878a.pth` is `102497337`, which is much close to pre-trained checkpoints.
```
drwxrwxr-x 3 scz0b6e scz0b6e      4096 Mar  5 16:29 20230305_162941
-rw-rw-r-- 1 scz0b6e scz0b6e         1 Mar  5 16:29 20230305_162941.py
-rw-rw-r-- 1 scz0b6e scz0b6e 204934911 Mar  5 16:30 epoch_1.pth
-rw-rw-r-- 1 scz0b6e scz0b6e 205060479 Mar  5 16:31 epoch_2.pth
-rw-rw-r-- 1 scz0b6e scz0b6e 205185407 Mar  5 16:32 epoch_3.pth
-rw-rw-r-- 1 scz0b6e scz0b6e 205310463 Mar  5 16:33 epoch_4.pth
-rw-rw-r-- 1 scz0b6e scz0b6e 102497337 Mar  5 17:08 epoch_5-6767878a.pth
-rw-rw-r-- 1 scz0b6e scz0b6e        57 Mar  5 16:34 last_checkpoint
```

Summarize example:
**not run pubulished_keys**

```
train_cfg=dict(by_epoch=True, max_epochs=5, val_interval=1)
```

***publish last checkpoints***

```
train_cfg=dict(by_epoch=True, max_epochs=5, val_interval=1, published_keys=['meta', 'state_dict'])
train_cfg=dict(by_epoch=True, max_epochs=5, val_interval=1, published_keys='state_dict')
```

***publish best checkpoints***

```
train_cfg=dict(interval=2, by_epoch=True, save_best='acc', rule='less', save_last=None, published_keys=['meta', 'state_dict'])
train_cfg=dict(interval=2, by_epoch=True, save_best='acc', rule='less', save_last=None, published_keys='state_dict')
```

***publish last and best checkpoints***

```
train_cfg=dict(interval=2, by_epoch=True, save_best='acc', rule='less', published_keys=['meta', 'state_dict'])
train_cfg=dict(interval=2, by_epoch=True, save_best='acc', rule='less', published_keys='state_dict')
```

***add another key which hope to publish***
```
train_cfg=dict(by_epoch=True, max_epochs=5, val_interval=1, published_keys=['meta', 'state_dict', `message_hub`])
train_cfg=dict(by_epoch=True, max_epochs=5, val_interval=1, published_keys=['state_dict', `message_hub`])
train_cfg=dict(by_epoch=True, max_epochs=5, val_interval=1, published_keys=`message_hub`)
```
