### ISSUE TITLE
[Docs] Requirements for the new EN set_interval.md document.

### ISSUE THREAD

**Issue by YuetianW** [open-mmlab/mmengine#962]
### 📚 The doc issue

I have completed the following translations and would like to add the corresponding md files:

> Translate "How to set the interval parameter" to English -> https://github.com/open-mmlab/mmengine/pull/959

I would like to add `set_interval.md` under `mmengine/docs/en/common_usage/` path.

**Comment by zhouzaida** [comment]
That would be better.

**Comment by zhouzaida** [comment]
closed by #964
