### ISSUE TITLE
[Feature] Align the evaluation result in log.

### ISSUE THREAD

**Issue by HAOCHENYE** [open-mmlab/mmengine#981]
### What is the feature?

As shown in the image, the `accuracy` is not aligned with the `eta`
![img_v2_386b1043-00bc-4bf9-99d8-5a79612d6a2g](https://user-images.githubusercontent.com/57566630/223367604-675740f1-5a77-4c6b-b481-eb53f6f531b8.jpg)

### Any other context?

No

**Comment by zhouzaida** [comment]
closed by #1034
